//! Process Version 2012 tone model (Lightroom's Basic panel tone sliders + base tone curve),
//! fitted to Adobe Camera Raw's measured behaviour (`tone_data.rs`, generated by
//! `src-tauri/tools/acr-oracle/tone_model.py`).
//!
//! Domain: EV of scene luminance relative to the raw clip (a neutral at the sensor's white
//! level = 0 EV), *before* exposure. Composition (validated against ACR renders of user-like
//! slider sets to ~2/255 mean error on a neutral ramp):
//! `Shadows -> Highlights -> Whites -> Exposure (+ baseline, with ACR's highlight shoulder)
//!  -> Contrast -> Blacks`, then the base tone curve (display-linear output).
//! Shadows/Highlights are evaluated on a local (edge-aware blurred) luminance by the
//! pipeline; the rest per pixel.

use super::tone_data as d;

/// Linear interpolation in a uniformly sampled table (clamped at the ends).
#[inline]
fn sample(table: &[f32], x0: f32, step: f32, x: f32) -> f32 {
    let t = ((x - x0) / step).max(0.0);
    let n = table.len() - 1;
    let i = (t as usize).min(n - 1);
    let f = (t - i as f32).min(1.0);
    table[i] + (table[i + 1] - table[i]) * f
}

/// Row of a slider table interpolated at `amount` (-100..=100).
fn slider_row(table: &[[f32; d::DELTA_N]], amount: f32) -> Option<Vec<f32>> {
    let a = amount.clamp(-100.0, 100.0);
    if a == 0.0 {
        return None;
    }
    let k = d::AMOUNTS.iter().position(|&v| v >= a).unwrap_or(d::AMOUNTS.len() - 1).max(1);
    let (a0, a1) = (d::AMOUNTS[k - 1], d::AMOUNTS[k]);
    let f = ((a - a0) / (a1 - a0)).clamp(0.0, 1.0);
    Some((0..d::DELTA_N).map(|j| table[k - 1][j] + (table[k][j] - table[k - 1][j]) * f).collect())
}

fn exposure_row(ev: f32) -> Vec<f32> {
    let e = ev.clamp(d::EXPOSURES[0], d::EXPOSURES[d::EXPOSURES.len() - 1]);
    let k = d::EXPOSURES.iter().position(|&v| v >= e).unwrap_or(d::EXPOSURES.len() - 1).max(1);
    let (e0, e1) = (d::EXPOSURES[k - 1], d::EXPOSURES[k]);
    let f = ((e - e0) / (e1 - e0)).clamp(0.0, 1.0);
    (0..d::DELTA_N).map(|j| d::EXPOSURE[k - 1][j] + (d::EXPOSURE[k][j] - d::EXPOSURE[k - 1][j]) * f).collect()
}

/// `e -> e + delta(e)` for one slider/exposure row.
struct Step {
    row: Vec<f32>,
    /// Constant EV offset added (exposure).
    offset: f32,
    /// Domain shift: the table is evaluated at `e + shift` (image-adaptive Highlights).
    shift: f32,
    highlights: bool,
}

impl Step {
    #[inline]
    fn apply(&self, e: f32) -> f32 {
        e + self.offset + sample(&self.row, d::DELTA_EV0, d::DELTA_STEP, e + self.shift)
    }
}

/// Mean log2 luminance of the calibration ramp the tables were measured on.
pub const KEY_CAL: f32 = -6.5;

/// The tone sliders of one render.
pub struct ToneModel {
    local: Vec<Step>,
    global: Vec<Step>,
}

/// Slider values the tone model uses (Lightroom units).
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct ToneSliders {
    pub exposure: f32,
    pub contrast: f32,
    pub highlights: f32,
    pub shadows: f32,
    pub whites: f32,
    pub blacks: f32,
}

impl ToneModel {
    /// `exposure` includes the baseline exposure.
    pub fn new(s: ToneSliders) -> Self {
        let step = |t: &[[f32; d::DELTA_N]], a: f32| {
            slider_row(t, a).map(|row| Step { row, offset: 0.0, shift: 0.0, highlights: false })
        };
        let hl = slider_row(&d::HIGHLIGHTS, s.highlights).map(|row| Step { row, offset: 0.0, shift: 0.0, highlights: true });
        let local = [step(&d::SHADOWS, s.shadows), hl].into_iter().flatten().collect();
        let mut global: Vec<Step> = step(&d::WHITES, s.whites).into_iter().collect();
        if s.exposure != 0.0 {
            global.push(Step { row: exposure_row(s.exposure), offset: s.exposure, shift: 0.0, highlights: false });
        }
        global.extend(step(&d::CONTRAST, s.contrast));
        global.extend(step(&d::BLACKS, s.blacks));
        ToneModel { local, global }
    }

    /// Image-adaptive Shadows/Highlights (fitted to Camera Raw renders of ramps of different
    /// ranges): Highlights act relative to the image's key (`key` = mean log2 luminance of
    /// the frame, pre-exposure EV), Shadows relative to its white (`white` = log2 of the
    /// brightest content, 0 = the raw clip).
    pub fn with_key(mut self, key: f32, white: f32) -> Self {
        let hl = (KEY_CAL - key).clamp(-8.0, 8.0);
        let sh = (-white).clamp(0.0, 10.0);
        for s in self.local.iter_mut() {
            s.shift = if s.highlights { hl } else { sh };
        }
        self
    }

    /// Shadows/Highlights have an effect.
    pub fn has_local(&self) -> bool {
        !self.local.is_empty()
    }

    /// EV delta of the local sliders at local (base) luminance `base_ev`.
    #[inline]
    pub fn local_delta(&self, base_ev: f32) -> f32 {
        let mut e = base_ev;
        for s in &self.local {
            e = s.apply(e);
        }
        e - base_ev
    }

    /// Whites, exposure, contrast, blacks: pre-exposure EV -> EV before the base curve.
    #[inline]
    pub fn global(&self, ev: f32) -> f32 {
        let mut e = ev;
        for s in &self.global {
            e = s.apply(e);
        }
        e
    }
}

/// Base tone curve (Camera Raw's default for profiles without `ProfileToneCurve`):
/// scene-linear (raw clip = 1 after exposure) -> display-linear 0..=1.
pub fn base_curve(x: f32) -> f32 {
    if x <= 0.0 {
        return 0.0;
    }
    let ev = x.log2();
    if ev < d::BASE_EV0 {
        return x * d::BASE_TOE_SLOPE;
    }
    if ev >= 0.0 {
        return 1.0;
    }
    sample(&d::BASE_CURVE, d::BASE_EV0, d::BASE_STEP, ev)
}

/// Base curve from a DCP `ProfileToneCurve` (x, y pairs over 0..=1, linear), else the
/// default.
pub fn profile_curve(points: Option<&[[f32; 2]]>) -> impl Fn(f32) -> f32 + '_ {
    move |x: f32| match points {
        Some(p) if p.len() >= 2 => {
            let x = x.clamp(0.0, 1.0);
            let i = p.partition_point(|q| q[0] <= x).clamp(1, p.len() - 1);
            let (a, b) = (p[i - 1], p[i]);
            if b[0] <= a[0] {
                return b[1];
            }
            a[1] + (b[1] - a[1]) * (x - a[0]) / (b[0] - a[0])
        }
        _ => base_curve(x),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn neutral_model_is_identity_and_curve_is_monotone() {
        let m = ToneModel::new(ToneSliders::default());
        assert!(!m.has_local());
        for e in [-12.0f32, -6.0, -2.5, -1.0, -0.2] {
            assert!((m.global(e) - e).abs() < 0.02, "{e} -> {}", m.global(e));
            assert_eq!(m.local_delta(e), 0.0);
        }
        let mut last = 0.0;
        for i in 1..=2000 {
            let x = i as f32 / 2000.0;
            let y = base_curve(x);
            assert!(y >= last, "monotone at {x}");
            last = y;
        }
        assert_eq!(base_curve(1.0), 1.0);
        assert_eq!(base_curve(2.0), 1.0);
        // Camera Raw renders scene mid-grey brightly (0.18 -> ~0.38 display linear).
        assert!((0.3..0.45).contains(&base_curve(0.18)), "{}", base_curve(0.18));
    }

    #[test]
    fn sliders_move_the_expected_way() {
        let at = |s: ToneSliders, e: f32| {
            let m = ToneModel::new(s);
            m.global(e + m.local_delta(e))
        };
        let base = ToneSliders::default();
        assert!(at(ToneSliders { exposure: 1.0, ..base }, -4.0) > -3.2);
        assert!(at(ToneSliders { shadows: 100.0, ..base }, -8.0) > -7.0);
        assert!(at(ToneSliders { highlights: -100.0, ..base }, -0.5) < -1.0);
        assert!(at(ToneSliders { blacks: 50.0, ..base }, -9.0) > -8.5);
        assert!(at(ToneSliders { whites: -50.0, ..base }, -0.3) < -0.4);
        let c = ToneSliders { contrast: 50.0, ..base };
        assert!(at(c, -6.0) < -6.2 && at(c, -1.0) > -0.95);
        // Monotone in the input for a strong user-like set.
        let u = ToneSliders { exposure: -0.5, contrast: -60.0, highlights: -66.0, shadows: 51.0, whites: -24.0, blacks: 63.0 };
        let m = ToneModel::new(u);
        let mut last = f32::NEG_INFINITY;
        for i in 0..200 {
            let e = -13.0 + i as f32 * 0.065;
            let y = m.global(e + m.local_delta(e));
            assert!(y >= last - 1e-4, "{e}: {y} < {last}");
            last = y;
        }
    }
}
