//! Process Version 2012 tone model (Lightroom's Basic panel tone sliders + base tone curve),
//! fitted to Adobe Camera Raw's measured behaviour (`tone_data.rs`, generated by
//! `src-tauri/tools/acr-oracle/tone_model.py`).
//!
//! Domain: EV of scene luminance relative to the raw clip (a neutral at the sensor's white
//! level = 0 EV), *before* exposure. Composition (validated against ACR renders of user-like
//! slider sets to ~2/255 mean error on a neutral ramp):
//! `Shadows -> Highlights -> Whites -> Exposure (+ baseline, with ACR's highlight shoulder)
//!  -> Contrast -> Blacks`, then the base tone curve (display-linear output).
//! Shadows/Highlights are evaluated on a local (edge-aware blurred) luminance by the
//! pipeline; the rest per pixel.

use super::local_tone_data as ld;
use super::tone_data as d;

/// Linear interpolation in a uniformly sampled table (clamped at the ends).
#[inline]
fn sample(table: &[f32], x0: f32, step: f32, x: f32) -> f32 {
    let t = ((x - x0) / step).max(0.0);
    let n = table.len() - 1;
    let i = (t as usize).min(n - 1);
    let f = (t - i as f32).min(1.0);
    table[i] + (table[i + 1] - table[i]) * f
}

/// Row of a slider table interpolated at `amount` (-100..=100).
fn slider_row(table: &[[f32; d::DELTA_N]], amount: f32) -> Option<Vec<f32>> {
    let a = amount.clamp(-100.0, 100.0);
    if a == 0.0 {
        return None;
    }
    let k = d::AMOUNTS.iter().position(|&v| v >= a).unwrap_or(d::AMOUNTS.len() - 1).max(1);
    let (a0, a1) = (d::AMOUNTS[k - 1], d::AMOUNTS[k]);
    let f = ((a - a0) / (a1 - a0)).clamp(0.0, 1.0);
    Some((0..d::DELTA_N).map(|j| table[k - 1][j] + (table[k][j] - table[k - 1][j]) * f).collect())
}

fn exposure_row(ev: f32) -> Vec<f32> {
    let e = ev.clamp(d::EXPOSURES[0], d::EXPOSURES[d::EXPOSURES.len() - 1]);
    let k = d::EXPOSURES.iter().position(|&v| v >= e).unwrap_or(d::EXPOSURES.len() - 1).max(1);
    let (e0, e1) = (d::EXPOSURES[k - 1], d::EXPOSURES[k]);
    let f = ((e - e0) / (e1 - e0)).clamp(0.0, 1.0);
    (0..d::DELTA_N).map(|j| d::EXPOSURE[k - 1][j] + (d::EXPOSURE[k][j] - d::EXPOSURE[k - 1][j]) * f).collect()
}

/// `e -> e + delta(e)` for one slider/exposure row.
struct Step {
    row: Vec<f32>,
    /// Constant EV offset added (exposure).
    offset: f32,
}

impl Step {
    #[inline]
    fn apply(&self, e: f32) -> f32 {
        e + self.offset + sample(&self.row, d::DELTA_EV0, d::DELTA_STEP, e)
    }
}

/// The global tone sliders of one render (Whites, Exposure, Contrast, Blacks).
pub struct ToneModel {
    global: Vec<Step>,
}

/// Slider values the tone model uses (Lightroom units).
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct ToneSliders {
    pub exposure: f32,
    pub contrast: f32,
    pub highlights: f32,
    pub shadows: f32,
    pub whites: f32,
    pub blacks: f32,
}

impl ToneModel {
    /// `exposure` includes the baseline exposure. Shadows/Highlights are ignored here (they
    /// are the local operator, [`LocalTone`]).
    pub fn new(s: ToneSliders) -> Self {
        let step = |t: &[[f32; d::DELTA_N]], a: f32| slider_row(t, a).map(|row| Step { row, offset: 0.0 });
        let mut global: Vec<Step> = step(&d::WHITES, s.whites).into_iter().collect();
        if s.exposure != 0.0 {
            global.push(Step { row: exposure_row(s.exposure), offset: s.exposure });
        }
        global.extend(step(&d::CONTRAST, s.contrast));
        global.extend(step(&d::BLACKS, s.blacks));
        ToneModel { global }
    }

    /// Whites, exposure, contrast, blacks: pre-exposure EV -> EV before the base curve.
    #[inline]
    pub fn global(&self, ev: f32) -> f32 {
        let mut e = ev;
        for s in &self.global {
            e = s.apply(e);
        }
        e
    }
}

/// Camera Raw's Shadows / Highlights as a local operator, fitted on real frames
/// (`local_tone_data.rs`, `tools/acr-oracle/fit_local.py`): the EV delta of a pixel is a
/// function of its *adaptation luminance* `m` (an edge-aware, multi-scale base of the
/// scene log luminance, see `pipeline::ToneContext`) relative to the image's reference
/// `KEY_WEIGHT * key + (1 - KEY_WEIGHT) * white`. Local detail (pixel - base) is kept, so
/// textures are not flattened; shadows in large dark areas are lifted more than small
/// dark details in bright surroundings, and low-key frames (night) are lifted less.
pub struct LocalTone {
    shadows: Option<Vec<f32>>,
    highlights: Option<Vec<f32>>,
}

fn local_row(table: &[[f32; ld::REL_N]; 5], amount: f32) -> Option<Vec<f32>> {
    let a = amount.clamp(-100.0, 100.0);
    if a == 0.0 {
        return None;
    }
    let k = ld::AMOUNTS.iter().position(|&v| v >= a).unwrap_or(ld::AMOUNTS.len() - 1).max(1);
    let (a0, a1) = (ld::AMOUNTS[k - 1], ld::AMOUNTS[k]);
    let f = ((a - a0) / (a1 - a0)).clamp(0.0, 1.0);
    Some((0..ld::REL_N).map(|j| table[k - 1][j] + (table[k][j] - table[k - 1][j]) * f).collect())
}

impl LocalTone {
    pub fn new(shadows: f32, highlights: f32) -> Self {
        LocalTone { shadows: local_row(&ld::SHADOWS, shadows), highlights: local_row(&ld::HIGHLIGHTS, highlights) }
    }

    pub fn is_identity(&self) -> bool {
        self.shadows.is_none() && self.highlights.is_none()
    }

    /// EV delta at an adaptation luminance `rel_s` / `rel_h` EV relative to the Shadows /
    /// Highlights references ([`Self::references`]).
    #[inline]
    pub fn delta(&self, rel_s: f32, rel_h: f32) -> f32 {
        let s = self.shadows.as_ref().map_or(0.0, |r| sample(r, ld::REL0, ld::REL_STEP, rel_s));
        let h = self.highlights.as_ref().map_or(0.0, |r| sample(r, ld::REL0, ld::REL_STEP, rel_h));
        s + h
    }

    /// The Shadows and Highlights references (pre-exposure EV) from the source's
    /// log-luminance statistics (pre-exposure) and the total exposure (slider + baseline).
    /// Each was fitted in post-exposure EV as a linear mix of statistics plus a clamped
    /// white; the coefficients need not sum to 1, so a reference can move with exposure.
    pub fn references(s: &super::pipeline::ToneStats, exposure: f32) -> (f32, f32) {
        let x = exposure;
        let (key, p50, p90, p95, p99, white) = (s.key + x, s.p50 + x, s.p90 + x, s.p95 + x, s.p99 + x, s.white + x);
        let rs = ld::S_ONE
            + ld::S_KEY * key
            + ld::S_P50 * p50
            + ld::S_P90 * p90
            + ld::S_P95 * p95
            + ld::S_P99 * p99
            + ld::S_WHITE * white
            + ld::S_WCLIP_W * white.min(ld::S_WCLIP);
        let rh = ld::H_ONE
            + ld::H_KEY * key
            + ld::H_P50 * p50
            + ld::H_P90 * p90
            + ld::H_P95 * p95
            + ld::H_P99 * p99
            + ld::H_WHITE * white
            + ld::H_WCLIP_W * white.min(ld::H_WCLIP);
        (rs - x, rh - x)
    }
}

/// Base tone curve (Camera Raw's default for profiles without `ProfileToneCurve`):
/// scene-linear (raw clip = 1 after exposure) -> display-linear 0..=1.
pub fn base_curve(x: f32) -> f32 {
    if x <= 0.0 {
        return 0.0;
    }
    let ev = x.log2();
    if ev < d::BASE_EV0 {
        return x * d::BASE_TOE_SLOPE;
    }
    if ev >= 0.0 {
        return 1.0;
    }
    sample(&d::BASE_CURVE, d::BASE_EV0, d::BASE_STEP, ev)
}

/// Base curve from a DCP `ProfileToneCurve` (x, y pairs over 0..=1, linear), else the
/// default.
pub fn profile_curve(points: Option<&[[f32; 2]]>) -> impl Fn(f32) -> f32 + '_ {
    move |x: f32| match points {
        Some(p) if p.len() >= 2 => {
            let x = x.clamp(0.0, 1.0);
            let i = p.partition_point(|q| q[0] <= x).clamp(1, p.len() - 1);
            let (a, b) = (p[i - 1], p[i]);
            if b[0] <= a[0] {
                return b[1];
            }
            a[1] + (b[1] - a[1]) * (x - a[0]) / (b[0] - a[0])
        }
        _ => base_curve(x),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn neutral_model_is_identity_and_curve_is_monotone() {
        let m = ToneModel::new(ToneSliders::default());
        let l = LocalTone::new(0.0, 0.0);
        assert!(l.is_identity());
        for e in [-12.0f32, -6.0, -2.5, -1.0, -0.2] {
            assert!((m.global(e) - e).abs() < 0.02, "{e} -> {}", m.global(e));
            assert_eq!(l.delta(e, e), 0.0);
        }
        let mut last = 0.0;
        for i in 1..=2000 {
            let x = i as f32 / 2000.0;
            let y = base_curve(x);
            assert!(y >= last, "monotone at {x}");
            last = y;
        }
        assert_eq!(base_curve(1.0), 1.0);
        assert_eq!(base_curve(2.0), 1.0);
        // Camera Raw renders scene mid-grey brightly (0.18 -> ~0.38 display linear).
        assert!((0.3..0.45).contains(&base_curve(0.18)), "{}", base_curve(0.18));
    }

    #[test]
    fn sliders_move_the_expected_way() {
        let g = |s: ToneSliders, e: f32| ToneModel::new(s).global(e);
        let base = ToneSliders::default();
        assert!(g(ToneSliders { exposure: 1.0, ..base }, -4.0) > -3.2);
        assert!(g(ToneSliders { blacks: 50.0, ..base }, -9.0) > -8.5);
        assert!(g(ToneSliders { whites: -50.0, ..base }, -0.3) < -0.4);
        let c = ToneSliders { contrast: 50.0, ..base };
        assert!(g(c, -6.0) < -6.2 && g(c, -1.0) > -0.95);
        // Local: shadows lift dark areas (a few EV below the reference), not bright ones;
        // highlights darken bright areas.
        let s = LocalTone::new(100.0, 0.0);
        assert!(s.delta(-5.0, -5.0) > 1.5, "{}", s.delta(-5.0, -5.0));
        assert!(s.delta(3.0, 3.0).abs() < 0.05);
        assert!(LocalTone::new(-100.0, 0.0).delta(-5.0, -5.0) < -1.5);
        let h = LocalTone::new(0.0, -100.0);
        assert!(h.delta(3.0, 3.0) < -1.0 && h.delta(-6.0, -6.0).abs() < 0.1);
        // Half the amount ~ half the effect.
        let half = LocalTone::new(50.0, 0.0).delta(-5.0, -5.0) / s.delta(-5.0, -5.0);
        assert!((0.3..0.7).contains(&half), "{half}");
    }

    /// For a uniform area (adaptation = pixel) the local response keeps the tone order:
    /// e + delta(e) is monotone for every amount, and the full user-like chain too.
    #[test]
    fn local_response_is_monotone() {
        for sh in [-100.0f32, -50.0, 0.0, 37.0, 64.0, 100.0] {
            for hl in [-100.0f32, -66.0, 0.0, 23.0, 100.0] {
                let l = LocalTone::new(sh, hl);
                let mut last = f32::NEG_INFINITY;
                for i in 0..400 {
                    let rel = -14.0 + i as f32 * 0.05;
                    let y = rel + l.delta(rel, rel);
                    assert!(y >= last - 1e-4, "S {sh} H {hl} at {rel}: {y} < {last}");
                    last = y;
                }
            }
        }
        let m = ToneModel::new(ToneSliders {
            exposure: -0.5,
            contrast: -60.0,
            highlights: -66.0,
            shadows: 51.0,
            whites: -24.0,
            blacks: 63.0,
        });
        let l = LocalTone::new(51.0, -66.0);
        let mut last = f32::NEG_INFINITY;
        for i in 0..200 {
            let e = -13.0 + i as f32 * 0.065;
            let y = m.global(e + l.delta(e + 3.0, e + 3.0));
            assert!(y >= last - 1e-4, "{e}: {y} < {last}");
            last = y;
        }
    }
}
