// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getCatalogState: () => typedError<CatalogState, AppError>(__TAURI_INVOKE("get_catalog_state")),
	/**  Also kicks a rescore (tags/scores/suggestions use the new shoot type's thresholds). */
	setShootType: (shootType: ShootType) => typedError<null, AppError>(__TAURI_INVOKE("set_shoot_type", { shootType })),
	/**  Also kicks a rescore (burst regrouping). */
	setBurstWindow: (ms: number) => typedError<null, AppError>(__TAURI_INVOKE("set_burst_window", { ms })),
	/**
	 *  Registers RAW files under `path` (fast: no decoding; new thumbnails start `pending`),
	 *  reads existing XMP sidecars (rating/pick/label, and crs: develop settings from v5) of new or
	 *  externally changed images, then kicks the background ingest pipeline (and analysis, if `autoAnalyze`) and
	 *  returns. Progress arrives as `importProgress` / `thumbnailReady` / `thumbnailFailed`
	 *  (and `analysis*`) events.
	 */
	importFolder: (path: string, options: ImportOptions) => typedError<ImportSummary, AppError>(__TAURI_INVOKE("import_folder", { path, options })),
	listImages: (query: ImageQuery) => typedError<ImagePage, AppError>(__TAURI_INVOKE("list_images", { query })),
	getImage: (id: number) => typedError<RawImageEntry, AppError>(__TAURI_INVOKE("get_image", { id })),
	setRating: (ids: number[], rating: number) => typedError<null, AppError>(__TAURI_INVOKE("set_rating", { ids, rating })),
	setPick: (ids: number[], pick: PickFlag) => typedError<null, AppError>(__TAURI_INVOKE("set_pick", { ids, pick })),
	setColorLabel: (ids: number[], label: "red" | "yellow" | "green" | "blue" | "purple" | null) => typedError<null, AppError>(__TAURI_INVOKE("set_color_label", { ids, label })),
	/**  Adds (`present = true`) or removes a tag as the user. Removing an auto tag suppresses it. */
	setUserTag: (ids: number[], tag: CullTag, present: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_user_tag", { ids, tag, present })),
	/**  Stored adjustments, or neutral defaults for an unedited image. */
	getAdjustments: (id: number) => typedError<ParametricAdjustments, AppError>(__TAURI_INVOKE("get_adjustments", { id })),
	/**
	 *  Persists `adjustments` and records a history entry labelled `label` (e.g. the slider
	 *  name). Call on slider release / debounced (not per drag frame: use `render_preview`
	 *  for live feedback). Consecutive saves with the same label within 1.5 s coalesce into
	 *  one entry; saving unchanged values is a no-op. Marks the sidecar dirty (crs:).
	 */
	saveAdjustments: (id: number, adjustments: ParametricAdjustments, label: string) => typedError<AdjustmentHistory, AppError>(__TAURI_INVOKE("save_adjustments", { id, adjustments, label })),
	/**
	 *  Re-extracts thumbnails/previews/EXIF for `ids` (e.g. after a failure). Resets them to
	 *  `pending` and returns immediately; results arrive as events. With `autoAnalyze`, the
	 *  new previews are re-analyzed.
	 */
	regenerateThumbnails: (ids: number[]) => typedError<null, AppError>(__TAURI_INVOKE("regenerate_thumbnails", { ids })),
	/**  Catalog-wide pending/ready/failed counts and whether the pipeline is running. */
	getImportStatus: () => typedError<ImportStatus, AppError>(__TAURI_INVOKE("get_import_status")),
	/**
	 *  Queues `scope` for the background analysis worker and returns immediately.
	 *  Progress: `analysisProgress`, `analysisReady`, `analysisFailed`, `analysisFinished`.
	 */
	analyzeImages: (scope: AnalysisScope) => typedError<null, AppError>(__TAURI_INVOKE("analyze_images", { scope })),
	/**  Stops the worker after the images in flight; remaining work stays pending. */
	cancelAnalysis: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_analysis")),
	getAnalysisStatus: () => typedError<AnalysisStatus, AppError>(__TAURI_INVOKE("get_analysis_status")),
	setAutoAnalyze: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_auto_analyze", { enabled })),
	/**  Effective thresholds for `shootType` (stored overrides over the defaults). */
	getCullThresholds: (shootType: ShootType) => typedError<CullThresholds, AppError>(__TAURI_INVOKE("get_cull_thresholds", { shootType })),
	/**
	 *  Stores thresholds for `shootType` (`null` resets to defaults). Kicks a rescore when
	 *  `shootType` is the catalog's current shoot type.
	 */
	setCullThresholds: (shootType: ShootType, thresholds: {
	/**  EAR below this means the eye is closed (`blink`). 0..=1; open eyes are ~0.24. */
	blinkEar: number,
	/**  Group shots: `blink` if *any* considered face blinks (else only the primary face). */
	requireAllEyesOpen: boolean,
	/**  Faces whose box height is below this share of the preview height are ignored. 0..=1. */
	minFaceSize: number,
	/**  Primary-face sharpness below this means `missed_focus`. 0..=1. */
	faceSharpnessMin: number,
	/**  Global sharpness below this (no usable face) means `missed_focus`/`motion_blur`. 0..=1. */
	globalSharpnessMin: number,
	/**  Mean luma below this means `underexposed`. 0..=1. */
	underexposedMeanLuma: number,
	/**  Share of shadow-clipped pixels above this means `underexposed`. 0..=1. */
	underexposedClipPct: number,
	/**  Share of highlight-clipped pixels above this means `overexposed`. 0..=1. */
	overexposedClipPct: number,
	/**  Max Hamming distance (0..=64) between 64-bit perceptual hashes of frames in one burst. */
	burstHashDistance: number,
	/**  `overall` at or above this suggests `pick`. 0..=1. */
	pickMinOverall: number,
	/**  `overall` below this suggests `reject`. 0..=1, `<= pickMinOverall`. */
	rejectMaxOverall: number,
	weights: ScoreWeights,
} | null) => typedError<null, AppError>(__TAURI_INVOKE("set_cull_thresholds", { shootType, thresholds })),
	/**  Faces from the last analysis (empty if unanalyzed); for face-crop zoom. */
	getFaces: (id: number) => typedError<FaceInfo[], AppError>(__TAURI_INVOKE("get_faces", { id })),
	/**  Burst groups with members, optionally limited to groups touching `folderId`. */
	listBurstGroups: (folderId: number | null) => typedError<BurstGroup[], AppError>(__TAURI_INVOKE("list_burst_groups", { folderId })),
	/**
	 *  Copies the engine's suggested rating/pick into the user's rating/pick for `ids`
	 *  (unanalyzed images skipped). Returns the number of images updated.
	 */
	applySuggestions: (ids: number[]) => typedError<number, AppError>(__TAURI_INVOKE("apply_suggestions", { ids })),
	/**
	 *  Entries for `ids`, in the given order (e.g. to refresh rows after events or batch
	 *  edits). Atomic: an unknown id fails with `not_found`.
	 */
	getImages: (ids: number[]) => typedError<RawImageEntry[], AppError>(__TAURI_INVOKE("get_images", { ids })),
	/**
	 *  Every id matching `query` in its sort order, ignoring `offset`/`limit`
	 *  (select-all, loupe navigation, batch actions over a filter).
	 */
	listImageIds: (query: ImageQuery) => typedError<number[], AppError>(__TAURI_INVOKE("list_image_ids", { query })),
	/**  Filter-bar facet counts for `folderId` (`null` = whole catalog). */
	getFilterCounts: (folderId: number | null) => typedError<FilterCounts, AppError>(__TAURI_INVOKE("get_filter_counts", { folderId })),
	/**
	 *  Writes `<basename>.xmp` sidecars for `ids` now (catalog wins; unrelated XMP fields are
	 *  preserved). Unknown ids -> `not_found`; per-file errors are listed in the report.
	 */
	writeXmp: (ids: number[]) => typedError<XmpSyncReport, AppError>(__TAURI_INVOKE("write_xmp", { ids })),
	/**
	 *  Reads rating/pick/label (and crs: develop settings, see `xmp::crs`) from existing sidecars
	 *  of `ids` into the catalog (sidecar wins).
	 *  Images without a sidecar are `skipped`; refetch `report.changed`.
	 */
	readXmp: (ids: number[]) => typedError<XmpSyncReport, AppError>(__TAURI_INVOKE("read_xmp", { ids })),
	/**  Turns automatic (debounced) sidecar writing on/off. Enabling flushes every dirty image. */
	setXmpAutoSync: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_xmp_auto_sync", { enabled })),
	getXmpStatus: () => typedError<XmpStatus, AppError>(__TAURI_INVOKE("get_xmp_status")),
	/**
	 *  Renders `adjustments` (live, unsaved) for image `id`. Latest-wins per (id, slot):
	 *  resolves `null` when a newer request for the same (id, slot) superseded this one
	 *  (ignore it). First call per image decodes the RAW (~0.3-0.8 s); later calls reuse it.
	 */
	renderPreview: (id: number, adjustments: ParametricAdjustments, options: RenderOptions) => typedError<{
	imageId: number,
	slot: RenderSlot,
	/**  Monotonic per (image, slot); larger = newer. */
	seq: number,
	/**
	 *  `sieve://localhost/render/<imageId>/<slot>?v=<seq>` on macOS
	 *  (`http://sieve.localhost/...` on Windows).
	 */
	url: string,
	/**  Output pixel size (orientation applied). */
	width: number,
	height: number,
	histogram: Histogram,
	/**  Wall time of this request inside the backend (decode if uncached + pipeline + encode). */
	renderMs: number,
	/**  `adjustments.lut` refers to a LUT not in the library; rendered without it. */
	lutMissing: boolean,
} | null, AppError>(__TAURI_INVOKE("render_preview", { id, adjustments, options })),
	/**  As-shot white balance and develop-source sizes (decodes the RAW if not cached). */
	getDevelopInfo: (id: number) => typedError<DevelopInfo, AppError>(__TAURI_INVOKE("get_develop_info", { id })),
	/**
	 *  Decodes `ids` into the develop cache in the background (e.g. filmstrip neighbours of
	 *  the image being edited). Returns immediately.
	 */
	prepareDevelop: (ids: number[]) => typedError<null, AppError>(__TAURI_INVOKE("prepare_develop", { ids })),
	getHistory: (id: number) => typedError<AdjustmentHistory, AppError>(__TAURI_INVOKE("get_history", { id })),
	/**  Steps back one history entry (no-op at the first). Marks the sidecar dirty. */
	undoAdjustments: (id: number) => typedError<EditState, AppError>(__TAURI_INVOKE("undo_adjustments", { id })),
	/**  Steps forward one history entry (no-op at the last). Marks the sidecar dirty. */
	redoAdjustments: (id: number) => typedError<EditState, AppError>(__TAURI_INVOKE("redo_adjustments", { id })),
	/**  Jumps to history entry `entryId` of image `id` (Lightroom's History panel click). */
	gotoHistory: (id: number, entryId: number) => typedError<EditState, AppError>(__TAURI_INVOKE("goto_history", { id, entryId })),
	/**
	 *  Pastes the `fields` groups of `adjustments` (the frontend's copied settings) onto
	 *  every image in `ids`; one "Paste Settings" history entry per changed image. Atomic.
	 */
	pasteSettings: (ids: number[], adjustments: ParametricAdjustments, fields: AdjustmentField[]) => typedError<null, AppError>(__TAURI_INVOKE("paste_settings", { ids, adjustments, fields })),
	/**
	 *  Copies the `fields` groups of `sourceId`'s stored adjustments onto `targetIds`
	 *  ("Sync Settings"). Atomic.
	 */
	syncSettings: (sourceId: number, targetIds: number[], fields: AdjustmentField[]) => typedError<null, AppError>(__TAURI_INVOKE("sync_settings", { sourceId, targetIds, fields })),
	/**  Resets `ids` to neutral adjustments ("Reset" history entry). Atomic. */
	resetAdjustments: (ids: number[]) => typedError<null, AppError>(__TAURI_INVOKE("reset_adjustments", { ids })),
	/**  Applies preset `presetId` (its `fields` only) to `ids` ("Preset: <name>"). Atomic. */
	applyPreset: (ids: number[], presetId: number) => typedError<null, AppError>(__TAURI_INVOKE("apply_preset", { ids, presetId })),
	/**  Presets sorted by name. */
	listPresets: () => typedError<Preset[], AppError>(__TAURI_INVOKE("list_presets")),
	/**  Creates (`id = null`) or overwrites a preset. Names are unique (case-insensitive). */
	savePreset: (id: number | null, name: string, adjustments: ParametricAdjustments, fields: AdjustmentField[]) => typedError<Preset, AppError>(__TAURI_INVOKE("save_preset", { id, name, adjustments, fields })),
	deletePreset: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_preset", { id })),
	/**  LUTs in the library, sorted by name. */
	listLuts: () => typedError<LutInfo[], AppError>(__TAURI_INVOKE("list_luts")),
	/**
	 *  Validates and copies a `.cube` file into the library. Idempotent per file content.
	 *  Invalid file -> `invalid_argument`.
	 */
	importLut: (path: string) => typedError<LutInfo, AppError>(__TAURI_INVOKE("import_lut", { path })),
	/**
	 *  Deletes a LUT from the library. If images still reference it, fails with
	 *  `invalid_argument` unless `force` (they then render without it, `lutMissing`).
	 */
	deleteLut: (id: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("delete_lut", { id, force })),
	/**  Which formats can be written here (WebP/HEIC depend on encoders), plus concurrency limits. */
	getExportCapabilities: () => typedError<ExportCapabilities, AppError>(__TAURI_INVOKE("get_export_capabilities")),
	/**  Built-in presets (read-only, negative ids) first, then user presets by name. */
	listExportPresets: () => typedError<ExportPreset[], AppError>(__TAURI_INVOKE("list_export_presets")),
	/**
	 *  Creates (`id = null`) or overwrites a user preset. Built-ins cannot be overwritten
	 *  (`invalid_argument`; save under a new name instead). Names are unique (case-insensitive).
	 */
	saveExportPreset: (id: number | null, name: string, settings: ExportSettings) => typedError<ExportPreset, AppError>(__TAURI_INVOKE("save_export_preset", { id, name, settings })),
	/**  Deletes a user preset (built-ins -> `invalid_argument`). */
	deleteExportPreset: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_export_preset", { id })),
	/**
	 *  Dry run: resolved output paths and which already exist (for the export dialog's
	 *  "N files exist" warning). No pixels are developed.
	 */
	planExport: (ids: number[], settings: ExportSettings) => typedError<ExportPlan, AppError>(__TAURI_INVOKE("plan_export", { ids, settings })),
	/**
	 *  Queues an export of `ids` (in this order; `{seq}` follows it; duplicates dropped) with
	 *  `settings` and returns the `queued` job immediately. Adjustments are snapshotted now.
	 *  `presetName` labels the job. Progress: `exportProgress`; end: `exportFinished`.
	 *  `settings.destination` must not be `choose`. Unknown ids -> `not_found`, nothing queued.
	 */
	exportImages: (ids: number[], settings: ExportSettings, presetName: string | null) => typedError<ExportJob, AppError>(__TAURI_INVOKE("export_images", { ids, settings, presetName })),
	/**
	 *  Cancels a queued or running job (files already written are kept). No-op for finished
	 *  jobs; unknown id -> `not_found`. The job ends with `exportFinished { cancelled: true }`.
	 */
	cancelExport: (jobId: number) => typedError<null, AppError>(__TAURI_INVOKE("cancel_export", { jobId })),
	/**  Queued/running jobs first, then recent finished jobs (newest first, max 50). */
	getExportJobs: () => typedError<ExportJob[], AppError>(__TAURI_INVOKE("get_export_jobs")),
	/**
	 *  Groups the images of `folderId` (all folders for `null`) into scenes by capture-time gaps
	 *  and appearance similarity (`options` `null` = defaults). Replaces the `auto` scenes in scope
	 *  (and `manual` ones if `replaceManual`); members of kept manual scenes are not regrouped;
	 *  anchor flags survive regrouping. Blocking until done (first run computes preview features,
	 *  ~10 ms/image in parallel; later runs reuse them); progress via `sceneProgress {task:
	 *  "detect"}`. Returns `list_scenes(folderId)`.
	 */
	detectScenes: (folderId: number | null, options: {
	/**  A capture-time gap longer than this always starts a new scene. 1000..=86_400_000 ms. */
	maxGapMs: number,
	/**
	 *  0..=1. Minimum appearance similarity (tone + colour features of the preview) for a frame
	 *  to stay in the running scene; lower = fewer, larger scenes. 0 = split on time gaps only.
	 */
	similarity: number,
	/**  Also replace manual scenes in scope (default: they and their members are left alone). */
	replaceManual: boolean,
} | null) => typedError<Scene[], AppError>(__TAURI_INVOKE("detect_scenes", { folderId, options })),
	/**  Scenes with a member in `folderId` (all for `null`), in capture order. */
	listScenes: (folderId: number | null) => typedError<Scene[], AppError>(__TAURI_INVOKE("list_scenes", { folderId })),
	getScene: (id: number) => typedError<Scene, AppError>(__TAURI_INVOKE("get_scene", { id })),
	/**
	 *  New `manual` scene from `imageIds` (non-empty; moved out of their current scenes; scenes
	 *  left empty are deleted).
	 */
	createScene: (imageIds: number[]) => typedError<Scene, AppError>(__TAURI_INVOKE("create_scene", { imageIds })),
	/**
	 *  Replaces the members of scene `id` (non-empty; images in other scenes are moved in).
	 *  The scene becomes `manual`; anchors that stay members are kept.
	 */
	setSceneMembers: (id: number, imageIds: number[]) => typedError<Scene, AppError>(__TAURI_INVOKE("set_scene_members", { id, imageIds })),
	/**  Marks the graded anchors of scene `id`: 0..=2 members (`[]` clears). Keeps the method. */
	setSceneAnchors: (id: number, anchorIds: number[]) => typedError<Scene, AppError>(__TAURI_INVOKE("set_scene_anchors", { id, anchorIds })),
	/**  Merges `ids` (>= 2 scenes) into `ids[0]` (`manual`; anchors kept up to 2, in `ids` order). */
	mergeScenes: (ids: number[]) => typedError<Scene, AppError>(__TAURI_INVOKE("merge_scenes", { ids })),
	/**
	 *  Splits scene `id` before member `firstImageId` (capture order; not the first member).
	 *  Returns `[id, newScene]`, both `manual`; anchors follow their images.
	 */
	splitScene: (id: number, firstImageId: number) => typedError<Scene[], AppError>(__TAURI_INVOKE("split_scene", { id, firstImageId })),
	/**  Deletes scene `id` (its images become unassigned; adjustments untouched). */
	deleteScene: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_scene", { id })),
	/**
	 *  Proposes relative grades for `targetIds` from 1-2 graded `anchorIds` (nothing is saved).
	 *  Anchors: 1..=2 distinct images; anchors listed in `targetIds` are skipped; duplicates
	 *  dropped; no targets left or more than `MatchOptions::MAX_TARGETS` -> `invalid_argument`;
	 *  unknown ids -> `not_found`. Blocking until all previews are ready (renders at 640 px; the
	 *  first render of an image decodes its RAW); progress via `sceneProgress {task: "match"}`.
	 *  Result in `targetIds` order.
	 */
	matchScene: (anchorIds: number[], targetIds: number[], options: MatchOptions) => typedError<MatchPreview[], AppError>(__TAURI_INVOKE("match_scene", { anchorIds, targetIds, options })),
	/**
	 *  Commits scene-match results: one history entry labelled `label` (default "Match Scene")
	 *  per image whose adjustments change. Atomic (unknown id -> `not_found`, invalid values ->
	 *  `invalid_argument`, nothing written). Marks sidecars dirty (crs:). Returns the changed ids.
	 */
	applySceneMatch: (applications: MatchApplication[], label: string | null) => typedError<number[], AppError>(__TAURI_INVOKE("apply_scene_match", { applications, label })),
	/**
	 *  Render-space statistics of image `id` rendered with `adjustments` (`null` = its stored
	 *  adjustments), whole frame or `region` (oriented, normalized). Same pixels as the editor
	 *  (LUT included) at 640 px. Used to verify matches (mean luma / neutral within tolerance).
	 */
	getRenderStats: (id: number, adjustments: {
	/**  Bumped when slider semantics change; stored alongside the JSON. */
	processVersion: number,
	whiteBalance: WhiteBalance,
	/**  EV, -5..=5 (`crs:Exposure2012`). */
	exposure: number,
	contrast: number,
	highlights: number,
	shadows: number,
	whites: number,
	blacks: number,
	texture: number,
	clarity: number,
	dehaze: number,
	vibrance: number,
	saturation: number,
	hsl: HslAdjustments,
	lut: LutRef | null,
} | null, region: {
	x: number,
	y: number,
	width: number,
	height: number,
} | null) => typedError<ImageStats, AppError>(__TAURI_INVOKE("get_render_stats", { id, adjustments, region })),
};

/** Events */
export const events = {
	analysisFailed: makeEvent<AnalysisFailed>("analysis-failed"),
	analysisFinished: makeEvent<AnalysisFinished>("analysis-finished"),
	analysisProgress: makeEvent<AnalysisProgress>("analysis-progress"),
	analysisReady: makeEvent<AnalysisReady>("analysis-ready"),
	exportFinished: makeEvent<ExportFinished>("export-finished"),
	exportProgress: makeEvent<ExportProgress>("export-progress"),
	importProgress: makeEvent<ImportProgress>("import-progress"),
	sceneProgress: makeEvent<SceneProgress>("scene-progress"),
	thumbnailFailed: makeEvent<ThumbnailFailed>("thumbnail-failed"),
	thumbnailReady: makeEvent<ThumbnailReady>("thumbnail-ready"),
	xmpSynced: makeEvent<XmpSynced>("xmp-synced"),
	xmpWriteFailed: makeEvent<XmpWriteFailed>("xmp-write-failed"),
};

/* Types */
/**
 *  Groups of `ParametricAdjustments` selectable in a fields mask (Lightroom's
 *  "Copy Settings" / preset checkboxes). `ALL` selects everything.
 */
export type AdjustmentField = 
/**  `whiteBalance` (mode + temperature + tint). */
"white_balance" | "exposure" | "contrast" | "highlights" | "shadows" | "whites" | "blacks" | "texture" | "clarity" | "dehaze" | "vibrance" | "saturation" | 
/**  `hsl.hue` (all 8 bands). */
"hsl_hue" | 
/**  `hsl.saturation` (all 8 bands). */
"hsl_saturation" | 
/**  `hsl.luminance` (all 8 bands). */
"hsl_luminance" | 
/**  `lut` (reference + amount; copying a `null` removes the target's LUT). */
"lut";

/**
 *  Linear per-image edit history (oldest first) with a cursor. Undo/redo move the cursor
 *  and make that entry's snapshot the image's adjustments; a new edit after an undo
 *  discards the entries after the cursor.
 */
export type AdjustmentHistory = {
	imageId: number,
	entries: HistoryEntry[],
	/**  Entry whose snapshot is the current adjustments; `null` = never edited (no entries). */
	currentEntryId: number | null,
	canUndo: boolean,
	canRedo: boolean,
};

/**  Analysis failed for an image (unreadable preview, model error). */
export type AnalysisFailed = {
	imageId: number,
	reason: string,
};

/**
 *  The worker went idle: bursts, tags, scores and suggestions are final for this run.
 *  Refetch the visible page and `getCatalogState()` (tag counts).
 */
export type AnalysisFinished = {
	/**  Images measured in this run (excluding failures). */
	analyzed: number,
	failed: number,
	/**  Stopped by `cancel_analysis`; remaining work stays pending. */
	cancelled: boolean,
	/**  Burst groups in the catalog after regrouping. */
	burstGroups: number,
};

/**
 *  Progress of the per-image stage of the analysis worker. Counts cover the current
 *  run (`total` grows while ingest keeps producing previews). `done` includes failures.
 *  Throttled like `ImportProgress`. `done == total` ends the per-image stage; burst
 *  grouping/rescoring follows and the run ends with `AnalysisFinished`.
 */
export type AnalysisProgress = {
	done: number,
	total: number,
	/**  Of `done`, how many failed. */
	failed: number,
};

/**
 *  An image's measurements, `QualityScore`, faces and auto tags were written.
 *  Burst membership / `duplicate_burst` may still change until `AnalysisFinished`.
 */
export type AnalysisReady = {
	imageId: number,
};

/**  What `analyze_images` should (re)process. */
export type AnalysisScope = 
/**
 *  Every image with a ready preview that is unanalyzed or out of date (new import,
 *  re-extracted preview, older `modelVersion`). What auto-analysis runs.
 */
{ kind: "pending" } | 
/**  Re-measure these images even if up to date. Unknown ids fail with `not_found`. */
{ kind: "images"; ids: number[] } | 
/**  Re-measure every image in this folder. */
{ kind: "folder"; folderId: number } | 
/**  Re-measure the whole catalog. */
{ kind: "all" } | 
/**
 *  No ML: recompute tags, scores, suggestions and burst groups from stored
 *  measurements (after a shoot type / threshold / burst window change).
 */
{ kind: "rescore" };

/**
 *  Catalog-wide analysis snapshot, so the UI can restore progress after a reload.
 *  `total = analyzed + failed + pending + waiting`.
 */
export type AnalysisStatus = {
	total: number,
	/**  Up to date with the current model version and preview. */
	analyzed: number,
	/**  Failed with the current model version (not retried until forced or re-extracted). */
	failed: number,
	/**  Have a ready preview and need (re)analysis. */
	pending: number,
	/**  No usable preview yet (thumbnail pending or failed). */
	waiting: number,
	/**  The background worker is currently working. */
	running: boolean,
};

/**  Error returned by every command. Serialized as `{ kind, message }`. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

/**  Bits per channel of the written file. On the wire: `"8"` / `"16"`. */
export type BitDepth = "8" | "16";

/**  A cluster of near-identical frames shot in quick succession. */
export type BurstGroup = {
	id: number,
	startedAtMs: number,
	endedAtMs: number,
	/**  Best frame of the burst; the others carry `duplicate_burst`. */
	keeperImageId: number | null,
	/**  Members in capture order (at least 2). */
	imageIds: number[],
};

export type CameraInfo = {
	make: CameraMake,
	model: string | null,
	sensorLayout: SensorLayout,
};

export type CameraMake = "sony" | "fujifilm" | "canon" | "other";

/**
 *  EXIF capture metadata. All optional: populated by the ingest pipeline (Phase 2),
 *  in the same pass that extracts the embedded preview.
 */
export type CaptureMeta = {
	/**
	 *  Capture time in ms, including sub-seconds (`SubSecTimeOriginal`), needed for
	 *  burst grouping. EXIF `DateTimeOriginal` is camera-local wall-clock time with no
	 *  zone, so it is stored as that wall-clock time *interpreted as UTC* ("naive" ms):
	 *  display with `timeZone: "UTC"`; differences between frames are exact.
	 */
	capturedAtMs: number | null,
	iso: number | null,
	shutterSeconds: number | null,
	aperture: number | null,
	focalLengthMm: number | null,
	lens: string | null,
};

export type CatalogState = {
	catalogPath: string,
	imageCount: number,
	shootType: ShootType,
	/**  Max gap between consecutive frames in one burst. */
	burstWindowMs: number,
	folders: FolderEntry[],
	/**  Counts of non-suppressed tags, for the filter bar. */
	tagCounts: TagCount[],
	/**
	 *  Root of the derived-file cache (`<app_cache_dir>` or `$SIEVE_CACHE`).
	 *  Thumbnails/previews live in `<cacheDir>/thumbs/`.
	 */
	cacheDir: string,
	/**  Analysis starts automatically after import / on launch (`set_auto_analyze`). */
	autoAnalyze: boolean,
	/**
	 *  Sidecars are written automatically after rating/pick/label/tag changes
	 *  (`set_xmp_auto_sync`). Default off.
	 */
	xmpAutoSync: boolean,
};

/**  JPEG chroma subsampling. `444` keeps full colour resolution (larger files). */
export type ChromaSubsampling = "444" | "422" | "420";

/**
 *  What to do when a target file already exists on disk. Two images of one job that
 *  expand to the same name always get unique suffixes (never overwrite each other).
 */
export type CollisionPolicy = 
/**  Append `-2`, `-3`, ... before the extension. */
"unique_suffix" | "overwrite" | 
/**  Leave the existing file; the image counts as `skipped`. */
"skip";

/**  Lightroom-compatible colour labels (`xmp:Label`). */
export type ColorLabel = "red" | "yellow" | "green" | "blue" | "purple";

/**  Granular reason a frame may be culled (or deliberately kept). */
export type CullTag = "blink" | "missed_focus" | "motion_blur" | 
/**  Intentional blur (panning, bokeh-heavy) — not a defect. */
"creative_blur" | "underexposed" | "overexposed" | "duplicate_burst";

export type CullTagEntry = {
	tag: CullTag,
	source: TagSource,
	/**  0..=1. User tags are always 1. */
	confidence: number,
	/**
	 *  The user dismissed this auto tag. Kept (not deleted) so re-analysis
	 *  does not resurrect it and filters stay non-destructive.
	 */
	suppressed: boolean,
};

/**
 *  Tag/score thresholds for one `ShootType`. Defaults come from
 *  `ml::thresholds::default_thresholds`; user overrides are stored per shoot type.
 *  Sharpness values use the same normalized 0..=1 scale as `QualityScore`.
 */
export type CullThresholds = {
	/**  EAR below this means the eye is closed (`blink`). 0..=1; open eyes are ~0.24. */
	blinkEar: number,
	/**  Group shots: `blink` if *any* considered face blinks (else only the primary face). */
	requireAllEyesOpen: boolean,
	/**  Faces whose box height is below this share of the preview height are ignored. 0..=1. */
	minFaceSize: number,
	/**  Primary-face sharpness below this means `missed_focus`. 0..=1. */
	faceSharpnessMin: number,
	/**  Global sharpness below this (no usable face) means `missed_focus`/`motion_blur`. 0..=1. */
	globalSharpnessMin: number,
	/**  Mean luma below this means `underexposed`. 0..=1. */
	underexposedMeanLuma: number,
	/**  Share of shadow-clipped pixels above this means `underexposed`. 0..=1. */
	underexposedClipPct: number,
	/**  Share of highlight-clipped pixels above this means `overexposed`. 0..=1. */
	overexposedClipPct: number,
	/**  Max Hamming distance (0..=64) between 64-bit perceptual hashes of frames in one burst. */
	burstHashDistance: number,
	/**  `overall` at or above this suggests `pick`. 0..=1. */
	pickMinOverall: number,
	/**  `overall` below this suggests `reject`. 0..=1, `<= pickMinOverall`. */
	rejectMaxOverall: number,
	weights: ScoreWeights,
};

/**  Facts about an image's develop source, for initializing the editor. */
export type DevelopInfo = {
	imageId: number,
	/**
	 *  The camera's as-shot white balance expressed as temperature/tint (from LibRaw's
	 *  camera multipliers and colour matrix); `null` if the file has none. Seeds the
	 *  Temp/Tint sliders when switching from `as_shot` to `custom`.
	 */
	asShot: WhiteBalanceValues | null,
	/**  Size of the cached develop source (half-size demosaic), orientation applied. */
	sourceWidth: number,
	sourceHeight: number,
	/**  Full sensor output size, orientation applied (Phase 6 export size). */
	fullWidth: number,
	fullHeight: number,
};

/**  Adjustments + history after an undo/redo/jump. */
export type EditState = {
	adjustments: ParametricAdjustments,
	history: AdjustmentHistory,
};

export type ErrorKind = "not_found" | "invalid_argument" | "io" | "database" | "internal";

/**  What the export engine can do here (`get_export_capabilities`). */
export type ExportCapabilities = {
	/**  One entry per `ExportFormatKind`, in enum order. */
	formats: ExportFormatInfo[],
	/**  Upper bound of images developed concurrently (see `docs/architecture.md`, "Export"). */
	maxParallel: number,
	/**  Memory budget shared by concurrently developed images, MiB. */
	memoryBudgetMb: number,
};

/**
 *  Output colour space; its ICC profile is always embedded (sRGB IEC61966-2.1,
 *  Display P3, Adobe RGB (1998)).
 */
export type ExportColorSpace = "srgb" | "display_p3" | "adobe_rgb";

/**  Where exported files go (`ExportSettings.subfolder` is appended in every case). */
export type ExportDestination = 
/**
 *  Ask at export time. Allowed in presets; the export dialog must replace it with
 *  `folder` before calling `export_images` / `plan_export` (they reject it).
 */
{ kind: "choose" } | 
/**  Absolute folder path; created (with the subfolder) if missing. */
{ kind: "folder"; path: string } | 
/**  Next to each RAW (its own folder). */
{ kind: "source_folder" };

/**  An image that could not be exported. */
export type ExportFailure = {
	imageId: number,
	/**  Source RAW file name (for display). */
	fileName: string,
	reason: string,
};

/**
 *  An export job ended (completed or cancelled). Emitted exactly once per job, also for a
 *  job cancelled while still queued. `get_export_jobs()` then shows its final state.
 */
export type ExportFinished = {
	jobId: number,
	succeeded: number,
	skipped: number,
	failed: ExportFailure[],
	/**  Stopped by `cancel_export`; images not yet started were not exported. */
	cancelled: boolean,
	/**  Resolved destination incl. subfolder; `null` for `source_folder`. */
	outputDir: string | null,
	/**  Wall time since the job started running (excludes time queued); 0 if it never ran. */
	elapsedMs: number,
};

/**
 *  File format and its encoder options. Quality values are 0..=100 (Lightroom scale,
 *  passed to the encoder as-is).
 */
export type ExportFormat = { kind: "jpeg"; quality: number; chromaSubsampling: ChromaSubsampling } | { kind: "tiff"; bitDepth: BitDepth; compression: TiffCompression } | { kind: "png"; bitDepth: BitDepth } | 
/**  `quality` is ignored when `lossless`. */
{ kind: "webp"; quality: number; lossless: boolean } | 
/**  8-bit HEVC in a HEIF container (macOS ImageIO). */
{ kind: "heic"; quality: number };

/**  Encoder availability for one format in this build / on this machine. */
export type ExportFormatInfo = {
	kind: ExportFormatKind,
	available: boolean,
	/**  Why it is unavailable (e.g. "HEIC encoder not available"); `null` when available. */
	reason: string | null,
	/**  Bit depths the encoder writes (JPEG/WebP/HEIC `["8"]`, TIFF/PNG `["8", "16"]`). */
	bitDepths: BitDepth[],
	/**  EXIF/XMP metadata can be embedded. ICC profiles are embedded for every available format. */
	supportsMetadata: boolean,
};

/**
 *  Output file formats. `webp` / `heic` depend on encoders: check
 *  `get_export_capabilities()` before offering them.
 */
export type ExportFormatKind = "jpeg" | "tiff" | "png" | "webp" | "heic";

/**  An export job (live or from history). */
export type ExportJob = {
	id: number,
	state: ExportJobState,
	/**  Label passed to `export_images` (usually the preset name). */
	presetName: string | null,
	format: ExportFormatKind,
	total: number,
	/**  `succeeded + failed + skipped`. */
	done: number,
	succeeded: number,
	failed: number,
	/**  Existing files left alone (`collision = skip`). */
	skipped: number,
	/**  Resolved destination incl. subfolder; `null` for `source_folder`. */
	outputDir: string | null,
	failures: ExportFailure[],
	createdAtMs: number,
	finishedAtMs: number | null,
};

export type ExportJobState = 
/**  Waiting for an earlier job (jobs run one at a time, in order). */
"queued" | "running" | 
/**  Every image was processed (some may have failed or been skipped). */
"completed" | 
/**  Stopped by `cancel_export`; files already written are kept. */
"cancelled" | 
/**  The app quit while the job was queued/running (not resumed). */
"interrupted";

/**  Dry run of an export: resolved paths, no pixels. Disk state may change before it runs. */
export type ExportPlan = {
	/**  Resolved destination incl. subfolder; `null` for `source_folder` (one per RAW folder). */
	outputDir: string | null,
	/**  In `ids` order. */
	files: PlannedFile[],
	/**  How many `files` have `exists`. */
	existing: number,
};

/**
 *  A named export configuration. Built-in presets (`builtIn`, negative ids) are read-only:
 *  "save as" creates a user preset.
 */
export type ExportPreset = {
	id: number,
	/**  Unique case-insensitively across built-in and user presets, 1..=100 chars (trimmed). */
	name: string,
	builtIn: boolean,
	settings: ExportSettings,
	/**  0 for built-ins. */
	createdAtMs: number,
	updatedAtMs: number,
};

/**
 *  Progress of the running export job. Throttled like `ImportProgress`. `done` includes
 *  failures and skips.
 */
export type ExportProgress = {
	jobId: number,
	done: number,
	total: number,
	/**  Of `done`, how many failed. */
	failed: number,
	/**  Of `done`, how many were skipped (`collision = skip`). */
	skipped: number,
	/**  Source RAW file name most recently started; `null` when none is in flight. */
	currentFile: string | null,
};

/**  Everything that defines an export (the body of an `ExportPreset`). */
export type ExportSettings = {
	format: ExportFormat,
	colorSpace: ExportColorSpace,
	resize: ResizeOptions,
	/**  `null` = no output sharpening. */
	sharpening: OutputSharpening | null,
	naming: FileNaming,
	destination: ExportDestination,
	/**
	 *  Relative path appended to the destination (e.g. `"Smith Wedding/Web"`); `null` = none.
	 *  `/`-separated; no `..`, `.`, empty components, `\` or `:`.
	 */
	subfolder: string | null,
	metadata: MetadataOptions,
};

export type ExposureStats = {
	/**  Share of pixels at the highlight clip point, 0..=1. */
	clippedHighlightsPct: number,
	/**  Share of pixels at the shadow clip point, 0..=1. */
	clippedShadowsPct: number,
	/**  Mean luminance, 0..=1. */
	meanLuma: number,
};

/**
 *  One detected face, for the loupe's face-crop zoom and per-face diagnostics.
 *  Raw measurements (`ear`, `sharpness`) are threshold-independent; the derived flags
 *  (`eyesOpen`, `blink`, `inFocus`) reflect the thresholds at the last (re)score.
 */
export type FaceInfo = {
	bbox: NormRect,
	/**  Eye centres from the detector keypoints; image-left and image-right. */
	leftEye: NormPoint,
	rightEye: NormPoint,
	/**  Detector confidence 0..=1. */
	detectionScore: number,
	/**  Eye Aspect Ratio of the less-open eye; `None` if landmarks were unusable. */
	ear: number | null,
	/**  Eye openness 0..=1 derived from `ear`; `None` if `ear` is `None`. */
	eyesOpen: number | null,
	/**  Normalized sharpness 0..=1 of the eye region (face crop if eyes unusable). */
	sharpness: number,
	/**  Eyes closed per `CullThresholds.blinkEar`. */
	blink: boolean,
	/**  `sharpness >= CullThresholds.faceSharpnessMin`. */
	inFocus: boolean,
	/**  The face that drives `QualityScore.faceSharpness` (largest / most central). */
	primary: boolean,
	/**
	 *  Face is large enough to be judged (`CullThresholds.minFaceSize`); smaller faces
	 *  are reported but ignored for tags and scores.
	 */
	considered: boolean,
};

/**
 *  Output file names. `template` grammar: literal text plus tokens in braces (see
 *  [`parse_filename_template`]); the format's extension is appended.
 */
export type FileNaming = {
	/**  e.g. `"{filename}"`, `"Smith-Wedding-{seq:4}"`, `"{date:YYYYMMDD}_{filename}"`. */
	template: string,
	/**  First value of `{seq}` (0..=999999999). */
	startNumber: number,
	collision: CollisionPolicy,
};

/**  Facet counts for the filter bar over one folder (or the whole catalog). */
export type FilterCounts = {
	total: number,
	/**  Non-suppressed tags; tags with no images are omitted. */
	tags: TagCount[],
	picked: number,
	rejected: number,
	unflagged: number,
	/**  `ratings[n]` = images with exactly `n` stars; always 6 entries. */
	ratings: number[],
	burstGroups: number,
	/**  Burst members hidden by `ImageQuery.collapseBursts`. */
	burstNonKeepers: number,
};

export type FolderEntry = {
	id: number,
	path: string,
	imageCount: number,
};

/**
 *  256-bin histograms of the rendered output (8-bit sRGB-encoded values, what the user
 *  sees). `luma` uses Rec.709 weights on the encoded values. Each vector has 256 entries;
 *  every channel sums to `width * height` of the render.
 */
export type Histogram = {
	red: number[],
	green: number[],
	blue: number[],
	luma: number[],
};

/**  One state in an image's edit history. */
export type HistoryEntry = {
	id: number,
	/**
	 *  e.g. "Exposure", "Paste Settings", "Preset: Warm", "Reset", "Read from XMP".
	 *  The first entry of every history is "Original" (the state before the first edit).
	 */
	label: string,
	createdAtMs: number,
};

export type HslAdjustments = {
	hue: HslChannels,
	saturation: HslChannels,
	luminance: HslChannels,
};

/**  Per-colour-band slider values, -100..=100 (Lightroom HSL / Color Mixer bands). */
export type HslChannels = {
	red: number,
	orange: number,
	yellow: number,
	green: number,
	aqua: number,
	blue: number,
	purple: number,
	magenta: number,
};

export type ImagePage = {
	items: RawImageEntry[],
	/**  Total matches ignoring offset/limit. */
	total: number,
};

/**
 *  Filter + page request for the grid. All filters are ANDed; empty lists / `null`
 *  mean "no constraint". Suppressed tags never match.
 */
export type ImageQuery = {
	/**  Combined with `tagMatch`. */
	includeTags: CullTag[],
	/**  Images carrying any of these are excluded. */
	excludeTags: CullTag[],
	tagMatch: TagMatch,
	/**  Image's pick flag is one of these (e.g. `["pick", "unflagged"]` hides rejects). */
	picks: PickFlag[],
	/**  Inclusive star range, 0..=5. */
	minRating: number | null,
	maxRating: number | null,
	/**  Image's colour label is one of these. */
	colorLabels: ColorLabel[],
	burstGroupId: number | null,
	/**  Only members of this scene. */
	sceneId?: number | null,
	/**
	 *  Hide burst members that are not their group's keeper (groups without a keeper
	 *  show all members); images outside bursts are unaffected.
	 */
	collapseBursts: boolean,
	folderId: number | null,
	sort: ImageSort,
	/**  Reverse the natural order of `sort` (images missing the key stay last). */
	sortDescending: boolean,
	offset: number,
	/**  Capped at [`ImageQuery::MAX_LIMIT`]. */
	limit: number,
};

/**  Natural order of each key; `ImageQuery.sortDescending` reverses it. */
export type ImageSort = 
/**  Oldest first; images without a capture time last. Ties by file name. */
"capture_time" | 
/**  A..Z. */
"file_name" | 
/**  Best `QualityScore.overall` first; unscored images last. */
"quality" | 
/**  Most stars first; ties in capture order. */
"rating";

/**
 *  Measurements of an image rendered through the develop pipeline with given adjustments
 *  (the same pixels the editor shows, LUT included), long edge `scene::STATS_MAX_EDGE`. The
 *  basis of scene matching and its acceptance checks.
 */
export type ImageStats = {
	imageId: number,
	/**  Measured area (oriented, normalized); `null` = whole frame. */
	region: NormRect | null,
	/**  Pixel size measured. */
	width: number,
	height: number,
	/**  Mean relative luminance (Rec.709 Y of the linearized sRGB output), 0..=1. */
	meanLuma: number,
	/**
	 *  log2 of the geometric mean luminance (Y floored at 2^-14). Exposure differences in EV
	 *  are differences of this value.
	 */
	logMeanLuma: number,
	percentiles: LumaPercentiles,
	/**  Share of pixels with any 8-bit channel >= 254. */
	clippedHighlights: number,
	/**  Share of pixels with all 8-bit channels <= 1. */
	clippedShadows: number,
	/**  Mean colour of the render. */
	meanOklab: OklabColor,
	neutral: NeutralEstimate,
	/**
	 *  White balance the measured adjustments resolve to (`as_shot` -> the camera's values);
	 *  `null` if as-shot and the file has none.
	 */
	whiteBalance: WhiteBalanceValues | null,
	/**  The camera's as-shot white balance (as in `DevelopInfo.asShot`). */
	asShot: WhiteBalanceValues | null,
	/**  The adjustments' LUT is missing from the library (measured without it). */
	lutMissing: boolean,
};

export type ImportOptions = {
	recursive: boolean,
};

/**
 *  Progress of the ingest pipeline (thumbnail + EXIF extraction).
 *  Counts cover the current pipeline run: images queued since the pipeline was last
 *  idle (new imports and regenerations join the running batch and grow `total`).
 *  `done` includes failures. `done == total` means the pipeline is idle.
 *  Throttled by the emitter (at most ~10 per second, plus a final one).
 */
export type ImportProgress = {
	done: number,
	total: number,
	/**  Of `done`, how many failed. */
	failed: number,
};

/**
 *  Snapshot of thumbnail/metadata extraction, so the UI can restore its progress
 *  display after a reload. Counts cover the whole catalog.
 */
export type ImportStatus = {
	total: number,
	pending: number,
	ready: number,
	failed: number,
	/**  The background pipeline is currently working. */
	running: boolean,
};

export type ImportSummary = {
	folderId: number,
	/**  New images added to the catalog. */
	added: number,
	/**  Supported files already in the catalog. */
	skipped: number,
	/**  Files with a RAW extension whose header did not match the format. */
	invalid: number,
	/**
	 *  Existing XMP sidecars whose rating/pick/label were read into the catalog
	 *  (new images, and unchanged images whose sidecar changed on disk).
	 */
	sidecarsRead: number,
};

/**  Relative luminance percentiles (linear, 0..=1) of a rendered image. */
export type LumaPercentiles = {
	p1: number,
	p10: number,
	p50: number,
	p90: number,
	p99: number,
};

/**  A `.cube` file in the LUT library (`<app_data>/luts/<id>.cube`, `$SIEVE_LUTS`). */
export type LutInfo = {
	id: string,
	/**  `TITLE` from the file, else the imported file's name without extension. */
	name: string,
	kind: LutKind,
	/**  Entries per axis (2..=65 for 3D, 2..=65536 for 1D). */
	size: number,
	/**  Absolute path of the library copy. */
	path: string,
};

export type LutKind = 
/**  `LUT_1D_SIZE`: per-channel curves. */
"lut_1d" | 
/**  `LUT_3D_SIZE`: RGB cube. */
"lut_3d";

/**
 *  A `.cube` LUT from the LUT library, applied after the parametric stage
 *  (on display-referred sRGB-encoded values, before output encoding).
 */
export type LutRef = {
	/**
	 *  `LutInfo.id` (library file stem). A missing LUT renders as if absent and sets
	 *  `RenderedPreview.lutMissing`.
	 */
	id: string,
	/**  Blend amount 0..=100 (100 = full LUT output). */
	amount: number,
};

/**  One image's adjustments to commit via `apply_scene_match`. */
export type MatchApplication = {
	imageId: number,
	adjustments: ParametricAdjustments,
};

/**  `full - base` of the corrected sliders (0 for groups not matched). */
export type MatchDelta = {
	/**  EV. */
	exposure: number,
	/**  Kelvin (slider units). */
	temperatureK: number,
	tint: number,
	contrast: number,
	whites: number,
	blacks: number,
};

/**
 *  Parameters of `match_scene`. Relative grading: every target starts from the anchor's
 *  look (`base`) and gets corrections (`delta`) that cancel measured differences in
 *  brightness / white point / tonal range, so it renders like the anchor.
 */
export type MatchOptions = {
	/**  Correct `exposure` so the target's rendered brightness matches the anchor's. */
	matchExposure: boolean,
	/**
	 *  Correct temperature/tint so the target's rendered neutral matches the anchor's
	 *  (the result is always `custom` white balance).
	 */
	matchWhiteBalance: boolean,
	/**  Small `contrast` / `whites` / `blacks` corrections from luminance percentiles. */
	matchTone: boolean,
	/**
	 *  0..=1: share of the correction applied (`adjustments = lerp(base, full, strength)`);
	 *  0 = the anchor's settings copied verbatim (like Sync Settings).
	 */
	strength: number,
	/**
	 *  Groups copied from the anchor into `base` (the target keeps its own values for the rest).
	 *  The groups a `match*` flag corrects are always taken from the anchor.
	 */
	copyFields: AdjustmentField[],
};

/**  Proposed grade for one target of `match_scene` (nothing is saved). */
export type MatchPreview = {
	targetId: number,
	/**
	 *  Anchor(s) this target was matched to: one, or both when the target lies between two
	 *  anchors in capture time (blended).
	 */
	anchorIds: number[],
	/**  Weight of `anchorIds[1]` when blended (0..=1), else 0. */
	anchorWeight: number,
	/**
	 *  Strength 0: the target's settings with the anchor's groups copied (white balance
	 *  resolved to `custom` when matched).
	 */
	base: ParametricAdjustments,
	/**  Strength 1: `base` plus the full correction. */
	full: ParametricAdjustments,
	/**
	 *  `ParametricAdjustments::lerp(base, full, options.strength)`; what `apply_scene_match`
	 *  should receive unless the UI changes the strength (then use `lerpAdjustments`).
	 */
	adjustments: ParametricAdjustments,
	delta: MatchDelta,
	/**  The anchor rendered with its own settings (blended when two anchors). */
	reference: ImageStats,
	/**  The target rendered with its current (stored) settings. */
	before: ImageStats,
	/**  The target rendered with `adjustments`. */
	predicted: ImageStats,
	/**
	 *  At strength 1 the target lands within `scene::TOLERANCE_EV` / `scene::TOLERANCE_AB`
	 *  of the reference.
	 */
	converged: boolean,
	/**  Human-readable caveats (clamped slider, no neutral found, LUT missing...). */
	notes: string[],
};

/**
 *  Which metadata is copied into exported files. Develop settings (`crs:`) and Sieve's
 *  culling tags (`Sieve|*`) are never exported. Orientation is always written as 1
 *  (pixels are rotated); the ICC profile and resolution are always present.
 */
export type MetadataInclude = 
/**
 *  EXIF of the RAW (camera, lens, exposure, capture time) + sidecar XMP/IPTC
 *  (creator, rights, title, description, rating, label; keywords per `includeKeywords`).
 */
"all" | 
/**  Copyright notice only (EXIF `Copyright` + `dc:rights`). */
"copyright_only" | 
/**
 *  Copyright + creator and IPTC creator contact info (`dc:creator`, EXIF `Artist`,
 *  `Iptc4xmpCore:CreatorContactInfo`).
 */
"copyright_and_contact" | "none";

export type MetadataOptions = {
	include: MetadataInclude,
	/**  Strip GPS EXIF and IPTC location fields (only matters for `all`). */
	removeLocation: boolean,
	/**
	 *  Copy the sidecar's keywords (`dc:subject` / `lr:hierarchicalSubject`, minus `Sieve|*`).
	 *  Only matters for `all`.
	 */
	includeKeywords: boolean,
	/**  Overrides the copyright notice from the RAW/sidecar (ignored for `none`), <= 500 chars. */
	copyright: string | null,
	/**  Overrides the creator/artist (used by `all` and `copyright_and_contact`), <= 500 chars. */
	creator: string | null,
};

/**
 *  Estimated colour of neutral surfaces in a *rendered* image (render space: sRGB/D65).
 *  A perfectly balanced render has `a = b = 0` (xy = D65 0.3127, 0.3290).
 */
export type NeutralEstimate = {
	/**  CIE 1931 chromaticity of the estimate. */
	x: number,
	y: number,
	/**  Oklab a/b of the estimate (colour cast direction and size). */
	a: number,
	b: number,
	/**  0..=1 share of pixels the estimate is based on; 0 = grey-world fallback (whole frame). */
	coverage: number,
};

/**  Point in normalized preview coordinates (see [`NormRect`]). */
export type NormPoint = {
	x: number,
	y: number,
};

/**
 *  Axis-aligned rectangle in normalized preview coordinates: 0..=1 of the preview's
 *  width/height, origin top-left, orientation already applied (same frame the UI shows).
 */
export type NormRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  A colour in Oklab (L 0..=1; a/b ~ -0.4..=0.4, 0 = neutral). */
export type OklabColor = {
	l: number,
	a: number,
	b: number,
};

/**  Output sharpening, applied after resizing to the output-encoded pixels. */
export type OutputSharpening = {
	media: SharpenMedia,
	amount: SharpenAmount,
};

/**
 *  Parametric develop settings. Field names and ranges mirror Adobe Camera Raw
 *  Process 2012+ (`crs:` XMP namespace) so XMP export is a 1:1 mapping.
 *  Stored JSON missing newer fields loads as neutral (see `db::repo::get_adjustments`).
 */
export type ParametricAdjustments = {
	/**  Bumped when slider semantics change; stored alongside the JSON. */
	processVersion: number,
	whiteBalance: WhiteBalance,
	/**  EV, -5..=5 (`crs:Exposure2012`). */
	exposure: number,
	contrast: number,
	highlights: number,
	shadows: number,
	whites: number,
	blacks: number,
	texture: number,
	clarity: number,
	dehaze: number,
	vibrance: number,
	saturation: number,
	hsl: HslAdjustments,
	lut: LutRef | null,
};

export type PickFlag = "pick" | "reject" | "unflagged";

/**  One file an export would write (`plan_export`). */
export type PlannedFile = {
	imageId: number,
	/**  Final absolute path after the collision policy; `null` when it would be skipped. */
	path: string | null,
	/**  The template's path already exists on disk (before the collision policy). */
	exists: boolean,
};

/**  A saved develop preset: applies `adjustments` restricted to `fields`. */
export type Preset = {
	id: number,
	/**  Unique (case-insensitive), 1..=100 chars. */
	name: string,
	adjustments: ParametricAdjustments,
	/**  Non-empty; groups outside it are ignored when applying. */
	fields: AdjustmentField[],
	createdAtMs: number,
	updatedAtMs: number,
};

/**  Culling-engine scores. All scores are normalized to 0..=1, higher is better. */
export type QualityScore = {
	overall: number,
	/**  Laplacian variance on the primary face crop; `None` when no face found. */
	faceSharpness: number | null,
	globalSharpness: number,
	/**  Eye-openness (from EAR) of the least-open detected face; `None` when no face. */
	eyesOpen: number | null,
	composition: number | null,
	faceCount: number,
	exposure: ExposureStats,
	/**  Identifies the model/algorithm set, so scores can be recomputed on upgrade. */
	modelVersion: string,
	/**
	 *  Engine's suggested star rating 0..=5. Never written to `RawImageEntry.rating`
	 *  except through `apply_suggestions`.
	 */
	suggestedRating: number,
	/**
	 *  Engine's suggested flag (burst non-keepers and hard defects lean `reject`).
	 *  Never written to `RawImageEntry.pick` except through `apply_suggestions`.
	 */
	suggestedPick: PickFlag,
};

/**  Supported RAW containers, in pipeline priority order. */
export type RawFormat = 
/**  Sony ARW (TIFF-based). */
"arw" | 
/**  Fujifilm RAF (X-Trans or Bayer). */
"raf" | 
/**  Canon CR3 (ISO-BMFF based). */
"cr3";

/**  One RAW file in the catalog, with everything the grid and loupe need. */
export type RawImageEntry = {
	id: number,
	folderId: number,
	path: string,
	fileName: string,
	format: RawFormat,
	camera: CameraInfo,
	capture: CaptureMeta,
	width: number | null,
	height: number | null,
	/**  EXIF orientation 1..=8. */
	orientation: number | null,
	fileSize: number,
	fileMtimeMs: number,
	thumbnail: ThumbnailState,
	/**  Star rating 0..=5. */
	rating: number,
	pick: PickFlag,
	colorLabel: ColorLabel | null,
	burstGroupId: number | null,
	/**  This image is its burst group's keeper. */
	isBurstKeeper: boolean,
	tags: CullTagEntry[],
	quality: QualityScore | null,
	hasEdits: boolean,
	/**  Sidecar sync state of the XMP-mapped values (rating, pick, label, tags, develop settings). */
	xmp: XmpSyncState,
	/**  Scene (lighting scenario) this image belongs to, if any (Phase 7). */
	sceneId: number | null,
	/**  This image is a graded anchor of its scene. */
	isSceneAnchor: boolean,
};

/**  How to render a preview. */
export type RenderOptions = {
	/**
	 *  Long edge of the output in px, 64..=8192 (use CSS size x devicePixelRatio).
	 *  Never upscaled beyond the develop source (`DevelopInfo.sourceWidth/Height`, or the
	 *  region's share of it).
	 */
	maxEdge: number,
	slot: RenderSlot,
	/**  Render only this part of the (orientation-corrected) frame; `null` = whole frame. */
	region: NormRect | null,
};

/**
 *  Independent latest-wins render stream per image. A newer request in the same
 *  (image, slot) supersedes older ones; different slots never cancel each other.
 */
export type RenderSlot = 
/**  The edited image in the loupe (slider feedback). */
"main" | 
/**  Before/after view (the frontend sends the "before" adjustments, e.g. neutral). */
"before" | 
/**  A zoomed region (`RenderOptions.region`), e.g. 1:1 loupe detail. */
"detail";

/**
 *  A finished preview render. Pixels are an in-memory JPEG (sRGB, quality ~90, 4:4:4)
 *  served by the `sieve` URI scheme at `url`; set it as an `<img src>` directly (do not
 *  pass it through `convertFileSrc`). The URL is unique per render (`?v=<seq>`).
 */
export type RenderedPreview = {
	imageId: number,
	slot: RenderSlot,
	/**  Monotonic per (image, slot); larger = newer. */
	seq: number,
	/**
	 *  `sieve://localhost/render/<imageId>/<slot>?v=<seq>` on macOS
	 *  (`http://sieve.localhost/...` on Windows).
	 */
	url: string,
	/**  Output pixel size (orientation applied). */
	width: number,
	height: number,
	histogram: Histogram,
	/**  Wall time of this request inside the backend (decode if uncached + pipeline + encode). */
	renderMs: number,
	/**  `adjustments.lut` refers to a LUT not in the library; rendered without it. */
	lutMissing: boolean,
};

/**
 *  Output size. Sizes refer to the orientation-corrected image; the aspect ratio is always
 *  preserved (no cropping). Rounding: the constrained edge is exact, the other rounds to nearest.
 */
export type ResizeMode = 
/**  Full resolution (`DevelopInfo.fullWidth x fullHeight`). */
{ kind: "none" } | 
/**  Longer side = `px`. */
{ kind: "long_edge"; px: number } | 
/**  Shorter side = `px`. */
{ kind: "short_edge"; px: number } | 
/**  Total pixels ~= `mp` x 1,000,000 (0.1..=200). */
{ kind: "megapixels"; mp: number } | 
/**  Fit within a `width` x `height` box (literal: not rotated for portrait frames). */
{ kind: "width_height"; width: number; height: number };

export type ResizeOptions = {
	mode: ResizeMode,
	/**  Never upscale: if the target is larger than full resolution, export full resolution. */
	dontEnlarge: boolean,
	/**
	 *  Pixels per inch written to the file (EXIF/TIFF resolution, JFIF density, PNG `pHYs`),
	 *  1..=4800. Does not change pixel dimensions.
	 */
	resolutionPpi: number,
};

/**
 *  A lighting scenario: consecutive frames shot under the same light, graded together from
 *  1-2 anchors. An image belongs to at most one scene.
 */
export type Scene = {
	id: number,
	/**  Folder of all members; `null` if they span folders (manual scenes only). */
	folderId: number | null,
	/**  Earliest / latest member capture time (`null` if no member has one). */
	startedAtMs: number | null,
	endedAtMs: number | null,
	/**  Members in capture order (images without a capture time last, by file name). Never empty. */
	imageIds: number[],
	/**  Graded reference frames (0..=`Scene::MAX_ANCHORS`), a subset of `imageIds`, in capture order. */
	anchorIds: number[],
	method: SceneMethod,
	createdAtMs: number,
	updatedAtMs: number,
};

/**  Parameters of `detect_scenes`. `null` on the wire = `SceneDetectOptions::default()`. */
export type SceneDetectOptions = {
	/**  A capture-time gap longer than this always starts a new scene. 1000..=86_400_000 ms. */
	maxGapMs: number,
	/**
	 *  0..=1. Minimum appearance similarity (tone + colour features of the preview) for a frame
	 *  to stay in the running scene; lower = fewer, larger scenes. 0 = split on time gaps only.
	 */
	similarity: number,
	/**  Also replace manual scenes in scope (default: they and their members are left alone). */
	replaceManual: boolean,
};

/**  How a scene's membership was decided. */
export type SceneMethod = 
/**  Created by `detect_scenes` and not edited since; replaced by the next detection. */
"auto" | 
/**
 *  Created or edited by the user (`create_scene`, `set_scene_members`, `merge_scenes`,
 *  `split_scene`); kept by `detect_scenes` unless `replaceManual`.
 */
"manual";

/**
 *  Progress of a running `detect_scenes` (feature extraction over previews) or `match_scene`
 *  (renders per target). Throttled (~10/s, always ending with `done == total`). Only drives a
 *  progress bar; the command's result arrives when it resolves.
 */
export type SceneProgress = {
	task: SceneTask,
	done: number,
	total: number,
};

/**  Long-running scene operation reported by the `sceneProgress` event. */
export type SceneTask = "detect" | "match";

/**
 *  Relative weights of the score components in `QualityScore.overall`.
 *  Non-negative; normalized by their sum (all-zero is invalid).
 */
export type ScoreWeights = {
	eyesOpen: number,
	faceSharpness: number,
	globalSharpness: number,
	exposure: number,
	composition: number,
};

/**
 *  Colour filter array layout; selects the demosaic algorithm.
 *  Fuji bodies can be either, so this is `unknown` until metadata is read.
 */
export type SensorLayout = "bayer" | "x_trans" | "unknown";

export type SharpenAmount = "low" | "standard" | "high";

/**  Lightroom output-sharpening target. */
export type SharpenMedia = "screen" | "matte" | "glossy";

/**  Shoot context; biases subject prioritization and tag thresholds. */
export type ShootType = "wedding" | "portrait" | "sports" | "event" | "landscape" | "general";

export type TagCount = {
	tag: CullTag,
	count: number,
};

export type TagMatch = 
/**  Image has at least one of `includeTags`. */
"any" | 
/**  Image has every one of `includeTags`. */
"all";

export type TagSource = 
/**  Emitted by the culling engine. */
"auto" | 
/**  Applied by the user. */
"user";

/**  Extraction failed for an image. Mirrors `ThumbnailState::Failed`. */
export type ThumbnailFailed = {
	imageId: number,
	reason: string,
};

/**
 *  An image's thumbnail (and preview) finished extracting and its EXIF is in the
 *  catalog. Mirrors `ThumbnailState::Ready`; refetch the entry for EXIF fields.
 */
export type ThumbnailReady = {
	imageId: number,
	/**  Absolute path of the 512 px thumbnail. */
	path: string,
	/**  Absolute path of the 2048 px preview, if produced. */
	previewPath: string | null,
	width: number,
	height: number,
};

/**
 *  Where the embedded preview for an image stands. Pixels are JPEG files under
 *  `<cacheDir>/thumbs/`; the frontend loads them with `convertFileSrc(path)`
 *  (Tauri asset protocol). Paths are absolute. Orientation is already applied.
 */
export type ThumbnailState = 
/**  Registered, not yet extracted (or queued for regeneration). */
{ status: "pending" } | { status: "ready"; 
/**  Grid thumbnail, long edge 512 px. */
path: string; 
/**
 *  Loupe preview, long edge 2048 px (smaller if the embedded JPEG is smaller).
 *  `None` if only the thumbnail could be produced.
 */
previewPath: string | null; 
/**  Pixel size of the thumbnail at `path` (after orientation). */
width: number; height: number } | 
/**  Extraction failed; `reason` is a human-readable message. */
{ status: "failed"; reason: string };

export type TiffCompression = "none" | "lzw" | 
/**  Deflate (Adobe "ZIP"). */
"zip";

/**  White balance. `AsShot` uses the camera's recorded multipliers. */
export type WhiteBalance = { mode: "as_shot" } | 
/**  `temperatureK` 2000..=50000, `tint` -150..=150 (Lightroom scale). */
{ mode: "custom"; temperatureK: number; tint: number };

/**  White balance as Lightroom shows it for RAW files. */
export type WhiteBalanceValues = {
	/**  Kelvin, 2000..=50000. */
	temperatureK: number,
	/**  -150..=150. */
	tint: number,
};

export type XmpFailure = {
	imageId: number,
	reason: string,
};

/**  Catalog-wide XMP sync snapshot. */
export type XmpStatus = {
	/**  Images with unwritten changes. */
	dirty: number,
	/**  Images whose last write/read failed. */
	failed: number,
	/**  The auto-sync writer is currently working. */
	running: boolean,
	/**  Same as `CatalogState.xmpAutoSync`. */
	autoSync: boolean,
};

/**
 *  Result of `write_xmp` / `read_xmp`. Per-image file errors do not fail the batch;
 *  they are listed in `failed` (and stored in `XmpSyncState.error`).
 */
export type XmpSyncReport = {
	/**  Sidecars written (`write_xmp`) or read (`read_xmp`). */
	succeeded: number,
	/**  `read_xmp`: images without a sidecar. `write_xmp`: always 0. */
	skipped: number,
	failed: XmpFailure[],
	/**
	 *  Images whose catalog rating/pick/label or develop settings changed as a result (reads only);
	 *  refetch them with `get_images`.
	 */
	changed: number[],
};

/**  Per-image XMP sidecar state (`<basename>.xmp` next to the RAW). */
export type XmpSyncState = {
	/**
	 *  Rating/pick/label/tags or develop settings (crs:) changed in the catalog since the
	 *  sidecar was last written.
	 */
	dirty: boolean,
	/**  Unix ms when catalog and sidecar last agreed (write or read); `None` = never synced. */
	syncedAtMs: number | null,
	/**  Reason of the last failed write/read; `None` after a success. */
	error: string | null,
};

/**
 *  The auto-sync writer finished a pass. `written`: sidecars now match the catalog.
 *  `read`: sidecars that were newer than the catalog's change (edited externally) and
 *  were read into the catalog instead; refetch those entries (`get_images`).
 */
export type XmpSynced = {
	written: number[],
	read: number[],
};

/**
 *  Auto-sync could not write (or read) an image's sidecar. Also stored in
 *  `XmpSyncState.error`; the image stays `dirty` and is retried on the next pass.
 */
export type XmpWriteFailed = {
	imageId: number,
	reason: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

