// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getCatalogState: () => typedError<CatalogState, AppError>(__TAURI_INVOKE("get_catalog_state")),
	setShootType: (shootType: ShootType) => typedError<null, AppError>(__TAURI_INVOKE("set_shoot_type", { shootType })),
	setBurstWindow: (ms: number) => typedError<null, AppError>(__TAURI_INVOKE("set_burst_window", { ms })),
	/**  Registers RAW files under `path`. Does not decode; thumbnails start `pending`. */
	importFolder: (path: string, options: ImportOptions) => typedError<ImportSummary, AppError>(__TAURI_INVOKE("import_folder", { path, options })),
	listImages: (query: ImageQuery) => typedError<ImagePage, AppError>(__TAURI_INVOKE("list_images", { query })),
	getImage: (id: number) => typedError<RawImageEntry, AppError>(__TAURI_INVOKE("get_image", { id })),
	setRating: (ids: number[], rating: number) => typedError<null, AppError>(__TAURI_INVOKE("set_rating", { ids, rating })),
	setPick: (ids: number[], pick: PickFlag) => typedError<null, AppError>(__TAURI_INVOKE("set_pick", { ids, pick })),
	setColorLabel: (ids: number[], label: "red" | "yellow" | "green" | "blue" | "purple" | null) => typedError<null, AppError>(__TAURI_INVOKE("set_color_label", { ids, label })),
	/**  Adds (`present = true`) or removes a tag as the user. Removing an auto tag suppresses it. */
	setUserTag: (ids: number[], tag: CullTag, present: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_user_tag", { ids, tag, present })),
	/**  Stored adjustments, or neutral defaults for an unedited image. */
	getAdjustments: (id: number) => typedError<ParametricAdjustments, AppError>(__TAURI_INVOKE("get_adjustments", { id })),
	saveAdjustments: (id: number, adjustments: ParametricAdjustments) => typedError<null, AppError>(__TAURI_INVOKE("save_adjustments", { id, adjustments })),
};

/** Events */
export const events = {
	analysisProgress: makeEvent<AnalysisProgress>("analysis-progress"),
	importProgress: makeEvent<ImportProgress>("import-progress"),
	thumbnailReady: makeEvent<ThumbnailReady>("thumbnail-ready"),
};

/* Types */
/**  Progress of the culling/analysis worker. */
export type AnalysisProgress = {
	done: number,
	total: number,
};

/**  Error returned by every command. Serialized as `{ kind, message }`. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type CameraInfo = {
	make: CameraMake,
	model: string | null,
	sensorLayout: SensorLayout,
};

export type CameraMake = "sony" | "fujifilm" | "canon" | "other";

/**  EXIF capture metadata. All optional: populated by thumbnail extraction (Phase 2). */
export type CaptureMeta = {
	/**  Capture time in unix ms, including sub-second precision (needed for burst grouping). */
	capturedAtMs: number | null,
	iso: number | null,
	shutterSeconds: number | null,
	aperture: number | null,
	focalLengthMm: number | null,
	lens: string | null,
};

export type CatalogState = {
	catalogPath: string,
	imageCount: number,
	shootType: ShootType,
	/**  Max gap between consecutive frames in one burst. */
	burstWindowMs: number,
	folders: FolderEntry[],
	/**  Counts of non-suppressed tags, for the filter bar. */
	tagCounts: TagCount[],
};

/**  Lightroom-compatible colour labels (`xmp:Label`). */
export type ColorLabel = "red" | "yellow" | "green" | "blue" | "purple";

/**  Granular reason a frame may be culled (or deliberately kept). */
export type CullTag = "blink" | "missed_focus" | "motion_blur" | 
/**  Intentional blur (panning, bokeh-heavy) — not a defect. */
"creative_blur" | "underexposed" | "overexposed" | "duplicate_burst";

export type CullTagEntry = {
	tag: CullTag,
	source: TagSource,
	/**  0..=1. User tags are always 1. */
	confidence: number,
	/**
	 *  The user dismissed this auto tag. Kept (not deleted) so re-analysis
	 *  does not resurrect it and filters stay non-destructive.
	 */
	suppressed: boolean,
};

export type ErrorKind = "not_found" | "invalid_argument" | "io" | "database" | "internal";

export type ExposureStats = {
	/**  Share of pixels at the highlight clip point, 0..=1. */
	clippedHighlightsPct: number,
	/**  Share of pixels at the shadow clip point, 0..=1. */
	clippedShadowsPct: number,
	/**  Mean luminance, 0..=1. */
	meanLuma: number,
};

export type FolderEntry = {
	id: number,
	path: string,
	imageCount: number,
};

export type HslAdjustments = {
	hue: HslChannels,
	saturation: HslChannels,
	luminance: HslChannels,
};

/**  Per-colour-band slider values, -100..=100 (Lightroom HSL / Color Mixer bands). */
export type HslChannels = {
	red: number,
	orange: number,
	yellow: number,
	green: number,
	aqua: number,
	blue: number,
	purple: number,
	magenta: number,
};

export type ImagePage = {
	items: RawImageEntry[],
	/**  Total matches ignoring offset/limit. */
	total: number,
};

/**  Filter + page request for the grid. Suppressed tags never match. */
export type ImageQuery = {
	includeTags: CullTag[],
	excludeTags: CullTag[],
	tagMatch: TagMatch,
	pick: PickFlag | null,
	minRating: number | null,
	burstGroupId: number | null,
	folderId: number | null,
	sort: ImageSort,
	offset: number,
	/**  Capped at [`ImageQuery::MAX_LIMIT`]. */
	limit: number,
};

export type ImageSort = "capture_time" | "file_name" | 
/**  Best `QualityScore.overall` first; unscored images last. */
"quality";

export type ImportOptions = {
	recursive: boolean,
};

/**  Progress of `import_folder` / metadata scan. */
export type ImportProgress = {
	done: number,
	total: number,
};

export type ImportSummary = {
	folderId: number,
	/**  New images added to the catalog. */
	added: number,
	/**  Supported files already in the catalog. */
	skipped: number,
	/**  Files with a RAW extension whose header did not match the format. */
	invalid: number,
};

/**  A 3D LUT (`.cube`) applied after the parametric stage. */
export type LutRef = {
	path: string,
	/**  Blend amount 0..=100. */
	amount: number,
};

/**
 *  Parametric develop settings. Field names and ranges mirror Adobe Camera Raw
 *  Process 2012+ (`crs:` XMP namespace) so XMP export is a 1:1 mapping.
 *  Stored JSON missing newer fields loads as neutral (see `db::repo::get_adjustments`).
 */
export type ParametricAdjustments = {
	/**  Bumped when slider semantics change; stored alongside the JSON. */
	processVersion: number,
	whiteBalance: WhiteBalance,
	/**  EV, -5..=5 (`crs:Exposure2012`). */
	exposure: number,
	contrast: number,
	highlights: number,
	shadows: number,
	whites: number,
	blacks: number,
	texture: number,
	clarity: number,
	dehaze: number,
	vibrance: number,
	saturation: number,
	hsl: HslAdjustments,
	lut: LutRef | null,
};

export type PickFlag = "pick" | "reject" | "unflagged";

/**  Culling-engine scores. All scores are normalized to 0..=1, higher is better. */
export type QualityScore = {
	overall: number,
	/**  Laplacian variance on the primary face crop; `None` when no face found. */
	faceSharpness: number | null,
	globalSharpness: number,
	/**  Eye-openness (from EAR) of the least-open detected face; `None` when no face. */
	eyesOpen: number | null,
	composition: number | null,
	faceCount: number,
	exposure: ExposureStats,
	/**  Identifies the model/algorithm set, so scores can be recomputed on upgrade. */
	modelVersion: string,
};

/**  Supported RAW containers, in pipeline priority order. */
export type RawFormat = 
/**  Sony ARW (TIFF-based). */
"arw" | 
/**  Fujifilm RAF (X-Trans or Bayer). */
"raf" | 
/**  Canon CR3 (ISO-BMFF based). */
"cr3";

/**  One RAW file in the catalog, with everything the grid and loupe need. */
export type RawImageEntry = {
	id: number,
	folderId: number,
	path: string,
	fileName: string,
	format: RawFormat,
	camera: CameraInfo,
	capture: CaptureMeta,
	width: number | null,
	height: number | null,
	/**  EXIF orientation 1..=8. */
	orientation: number | null,
	fileSize: number,
	fileMtimeMs: number,
	thumbnail: ThumbnailState,
	/**  Star rating 0..=5. */
	rating: number,
	pick: PickFlag,
	colorLabel: ColorLabel | null,
	burstGroupId: number | null,
	tags: CullTagEntry[],
	quality: QualityScore | null,
	hasEdits: boolean,
};

/**
 *  Colour filter array layout; selects the demosaic algorithm.
 *  Fuji bodies can be either, so this is `unknown` until metadata is read.
 */
export type SensorLayout = "bayer" | "x_trans" | "unknown";

/**  Shoot context; biases subject prioritization and tag thresholds. */
export type ShootType = "wedding" | "portrait" | "sports" | "event" | "landscape" | "general";

export type TagCount = {
	tag: CullTag,
	count: number,
};

export type TagMatch = 
/**  Image has at least one of `includeTags`. */
"any" | 
/**  Image has every one of `includeTags`. */
"all";

export type TagSource = 
/**  Emitted by the culling engine. */
"auto" | 
/**  Applied by the user. */
"user";

/**  An embedded preview finished extracting. */
export type ThumbnailReady = {
	imageId: number,
	path: string,
	width: number,
	height: number,
};

/**
 *  Where the embedded preview for an image stands. Pixels are files in the app
 *  cache dir; the frontend loads `path` via Tauri's asset protocol.
 */
export type ThumbnailState = { status: "pending" } | { status: "ready"; path: string; width: number; height: number } | { status: "failed"; reason: string };

/**  White balance. `AsShot` uses the camera's recorded multipliers. */
export type WhiteBalance = { mode: "as_shot" } | 
/**  `temperatureK` 2000..=50000, `tint` -150..=150 (Lightroom scale). */
{ mode: "custom"; temperatureK: number; tint: number };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

