"""Generates `src/develop/local_tone_data.rs`: Shadows / Highlights response tables of the
local tone operator (see fit_local.py for the model), fitted on the fit set.

    python3 gen_local.py [--print]
"""
import os, sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fit_local as fl

# Fitted configuration (fit_local.py grid search, 2026-09-30): radii in px at a 2048 px long
# edge, eps in EV^2, weights of the two guided-filter bases (pixel weight 0), reference mix.
R1, R2, EPS, W1, W2, LAM = 64, 256, 1.0, 0.5, 0.5, 0.75
SMOOTH = 3.0
REF_NAMES = ["one", "key", "p50", "p90", "p95", "p99", "white", "wclip"]
REF = {"key": LAM, "white": 1 - LAM}
WCLIP = -1.0


def fit_T(data, variant, zero_side):
    X, Y = [], []
    for im in data:
        m = W1 * im["f"][(R1, EPS)] + W2 * im["f"][(R2, EPS)]
        rel = m - (LAM * im["key"] + (1 - LAM) * im["white"])
        d = im["d"][variant]
        ok = np.isfinite(d)
        X.append(fl.hat(rel[ok]))
        Y.append(d[ok])
    X, Y = np.vstack(X), np.concatenate(Y)
    K = X.shape[1]
    D = np.diff(np.eye(K), 2, axis=0)
    cnt = X.sum(0)
    # Anchor: the slider has no effect far on its inactive side.
    P = np.zeros(K)
    if zero_side == "bright":
        P[fl.KNOTS >= 2.0] = 1e4
    else:
        P[fl.KNOTS <= -9.0] = 1e4
    A = X.T @ X + SMOOTH * len(Y) / K * 1e-2 * D.T @ D + np.diag(P) + 1e-6 * np.eye(K)
    T = np.linalg.solve(A, X.T @ Y)
    rmse = np.sqrt(np.mean((Y - X @ T) ** 2))
    return T, rmse, cnt


def main():
    out = {}
    for slider, zero in [("S", "bright"), ("H", "dark")]:
        vs = ["n%s%+d" % (slider, a) for a in (-100, -50, 50, 100)]
        data = [fl.image_data(st, vs, [R1, R2], [EPS]) for st in fl.stems()]
        rows = []
        for v in vs:
            T, rmse, cnt = fit_T(data, v, zero)
            print(v, "rmse %.3f" % rmse, " ".join("%.1f:%+.2f" % (k, t) for k, t in zip(fl.KNOTS[::2], T[::2])))
            rows.append(T)
        out[slider] = rows
    if "--print" in sys.argv:
        return
    lines = [
        "//! Generated by `tools/acr-oracle/gen_local.py` from Camera Raw 17.5 renders of real frames",
        "//! (single-slider variants of the fit set). Do not edit by hand.",
        "#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]",
        "",
        "/// Guided-filter box radii (px at a 2048 px long edge), eps (EV^2), base weights.",
        "pub const RADIUS_FINE: f32 = %.1f;" % R1,
        "pub const RADIUS_COARSE: f32 = %.1f;" % R2,
        "pub const EPS: f32 = %.3f;" % EPS,
        "pub const WEIGHT_FINE: f32 = %.3f;" % W1,
        "/// Image reference (post-exposure EV) = REF_ONE + sum REF_<stat> * stat (+ exposure)",
        "/// with WCLIP = the clamp of the clamped white statistic.",
    ] + ["pub const REF_%s: f32 = %.4f;" % (k.upper(), REF.get(k, 0.0)) for k in REF_NAMES] + [
        "pub const WCLIP: f32 = %.3f;" % WCLIP,
        "/// Table domain: EV relative to the reference.",
        "pub const REL0: f32 = %.1f;" % fl.KNOTS[0],
        "pub const REL_STEP: f32 = 0.5;",
        "pub const REL_N: usize = %d;" % len(fl.KNOTS),
        "/// Slider amounts of the table rows.",
        "pub const AMOUNTS: [f32; 5] = [-100.0, -50.0, 0.0, 50.0, 100.0];",
    ]
    for slider, name in [("S", "SHADOWS"), ("H", "HIGHLIGHTS")]:
        rows = out[slider]
        rows = rows[:2] + [np.zeros(len(fl.KNOTS))] + rows[2:]
        lines.append("/// EV delta (at the adaptation luminance) per amount row.")
        lines.append("pub const %s: [[f32; REL_N]; 5] = [" % name)
        for r in rows:
            lines.append("    [" + ", ".join("%.4f" % v for v in r) + "],")
        lines.append("];")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src", "develop", "local_tone_data.rs")
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(path))


if __name__ == "__main__":
    main()
