"""Fits the Lightroom parametric (region) curve shapes to the ACR oracle measurements."""
import json, sys, numpy as np
HERE = __file__.rsplit("/", 1)[0]
C = json.load(open(HERE + "/curves.json"))
base = np.array(json.load(open(HERE + "/ramp.json"))["res"]["default"]) / 255.0
RES = {k: np.array(v)[:, 1] / 255.0 for k, v in C["res"].items()}
SETS = C["sets"]
NB = 64

def warp(t, r, s1, s2, s3):
    """Region-local coordinate u in [0,1] and region width (scale)."""
    t = np.clip(t, 1e-6, 1 - 1e-6)
    if r == "Shadows":
        g = np.log(0.5) / np.log(s1 / s2)
        return np.where(t < s2, (t / s2) ** g, 1.0), s2
    if r == "Highlights":
        g = np.log(0.5) / np.log((s3 - s2) / (1 - s2))
        return np.where(t > s2, ((t - s2) / (1 - s2)) ** g, 0.0), 1 - s2
    g = np.log(0.5) / np.log(s2)
    return t ** g, 1.0

def unwarp(u, t, r, s1, s2, s3):
    if r == "Shadows":
        g = np.log(0.5) / np.log(s1 / s2)
        return np.where(t < s2, s2 * u ** (1 / g), t)
    if r == "Highlights":
        g = np.log(0.5) / np.log((s3 - s2) / (1 - s2))
        return np.where(t > s2, s2 + (1 - s2) * u ** (1 / g), t)
    g = np.log(0.5) / np.log(s2)
    return u ** (1 / g)

REGIONS = ["Shadows", "Darks", "Lights", "Highlights"]
SHAPES = {}
for r in REGIONS:
    for sign in [-1, 1]:
      for amt in [50, 100]:
        us, vs = [], []
        for a in [amt]:
            for suffix, splits in [("", (0.25, 0.5, 0.75)), ("_u", (0.15, 0.35, 0.75))]:
                k = "%s%d%s" % (r, sign * a, suffix)
                o = RES[k]
                m = (base > 0.01) & (base < 0.97)
                if sign < 0:
                    m &= o > 0.004
                if sign > 0:
                    m &= o < 0.996
                u, w = warp(base[m], r, *splits)
                uo, _ = warp(o[m], r, *splits)
                keep = (u > 0) & (u < 1)
                us.append(u[keep])
                vs.append((uo - u)[keep])
        u = np.concatenate(us); v = np.concatenate(vs)
        shape = np.zeros(NB + 1)
        cnt = np.zeros(NB + 1)
        for uu, vv in zip(u, v):
            i = int(round(uu * NB))
            shape[i] += vv; cnt[i] += 1
        known = cnt > 0
        shape[known] /= cnt[known]
        grid = np.linspace(0, 1, NB + 1)
        shape = np.interp(grid, grid[known], shape[known])
        # Region endpoints are fixed.
        if r == "Shadows":
            shape[0] = 0.0; shape[-1] = 0.0
        if r == "Highlights":
            shape[0] = 0.0; shape[-1] = 0.0
        if r in ("Darks", "Lights"):
            shape[0] = 0.0; shape[-1] = 0.0
        # Light smoothing.
        sm = shape.copy()
        for i in range(1, NB):
            sm[i] = 0.25 * shape[i - 1] + 0.5 * shape[i] + 0.25 * shape[i + 1]
        SHAPES[(r, sign, amt)] = sm

def curve(t, params):
    s1 = params.get("ParametricShadowSplit", 25) / 100.0
    s2 = params.get("ParametricMidtoneSplit", 50) / 100.0
    s3 = params.get("ParametricHighlightSplit", 75) / 100.0
    out = t.copy()
    grid = np.linspace(0, 1, NB + 1)
    for r in REGIONS:
        a = params.get("Parametric" + r, 0) / 100.0
        if a == 0:
            continue
        u, w = warp(out, r, s1, s2, s3)
        sg = 1 if a > 0 else -1
        m = abs(a)
        s50 = np.interp(u, grid, SHAPES[(r, sg, 50)]); s100 = np.interp(u, grid, SHAPES[(r, sg, 100)])
        if m <= 0.5:
            d = 2 * m * s50
        else:
            f = (m - 0.5) / 0.5
            d = s50 * (1 - f) + s100 * f
        u2 = np.clip(u + d, 0, 1)
        out = unwarp(u2, out, r, s1, s2, s3)
    out = np.clip(out, 0, 1)
    return np.maximum.accumulate(out)

tot = []
for k, (c, s) in SETS.items():
    if s:
        continue
    p = curve(base, {kk: float(v) for kk, v in c.items()})
    e = np.abs(p - RES[k])[(base > 0.01)] * 255
    tot.append(e.mean())
    print("%-18s mean %.2f max %.2f" % (k, e.mean(), e.max()))
print("overall %.2f" % np.mean(tot))
if len(sys.argv) > 1:
    with open(sys.argv[1], "w") as f:
        f.write("//! Generated by tools/acr-oracle/param_model.py from Adobe Camera Raw measurements:\n")
        f.write("//! Lightroom parametric tone-curve region shapes (per region and sign) over the region's\n")
        f.write("//! split-warped coordinate u in 0..=1 (`PARAM_N + 1` samples), in units of the region width.\n#![allow(clippy::approx_constant)]\n\n")
        f.write("pub const PARAM_N: usize = %d;\n" % NB)
        for r in REGIONS:
            for sign, nm in [(1, "POS"), (-1, "NEG")]:
                for amt in [50, 100]:
                    f.write("pub const %s_%s_%d: [f32; %d] = [%s];\n" % (r.upper(), nm, amt, NB + 1, ", ".join("%.5f" % v for v in SHAPES[(r, sign, amt)])))
